kulshekhar/ts-jest

src/index.ts
src/utils.ts
tests/__tests__/tsconfig-default.spec.ts
tests/__tests__/tsconfig-inline.spec.ts
tests/__tests__/tsconfig-string.spec.ts
tests/button/package.json
tests/simple/package.json

#22 fix. And some small improvements in tests (they are working with part of sources in watch mode).
Fix and test for `null` and empty values in `globals` and `globals.__TS_CONFIG__`.

Fixing tsconfig issues.

---

README.md
coverageprocessor.js
package.json
src/coverageprocessor.ts
src/index.ts
src/preprocessor.ts
src/utils.ts

This PR adds code coverage remapping after tests completes, using [testresultsprocessor](https://facebook.github.io/jest/docs/configuration.html#testresultsprocessor-string) .
`jest` does not exposes hook to process code coverage after test completes, but provides hook for processing test results `testresultsprocessor`. This PR utilizes those to post process code coverage remapping. Unfortunately this hook is bit limited to post process coverage since this hook is being invoked after coverage processing is done, reason implementation has some workarounds.
as same as configuring preprosessor, setting result processor will enable coverage remapping. processor will honor most of coverage configuration.
```js
{
"scriptPreprocessor": "<rootDir>/node_modules/ts-jest/preprocessor.js", …
```

Support code coverage remapping

---

README.md
src/preprocessor.ts

While I need to follow up https://github.com/kulshekhar/ts-jest/issues/26, I've added small enhancement to not to store transpiled source into cache, if give file matches with `testRegex` which does not being included in code coverage.
Also added small documentation note can cause failure if cache does not cleared up for existing sources.

Do not store test case source maps into cache

---

package.json
src/coverageprocessor.ts
src/preprocessor.ts
tests/__tests__/jestconfig-json.spec.ts
tests/__tests__/jestconfig-package.spec.ts
tests/__tests__/ts-coverage.spec.ts
tests/__tests__/ts-errors.spec.ts
tests/jestconfig-test/jest.json
tests/simple/Hello.ts
tests/simple/package.json

related to #26 .
This PR adds basic integration test for coverage remapping result processor, tests basic flows from reading config to generating coverage.

Add basic tests for coverage remapping

---

.travis.yml

This should help keep us aware of any breakages that we might encounter in the future

Add node 7.x to travis config (failure allowed)

---

src/coverageprocessor.ts

This PR adds small guards to collect / remap coverage if non expected (mostly `null | undefined`) leads into whole remapping fails. Instead, it try to skip / deliver empty values.

Prevent failure when unexpected value passed

---

package.json
src/coverageprocessor.ts
tests/simple/NullCoverage.js
tests/simple/package.json
tests/simple/tsconfig.json

This PR adds missing test coverage from PR https://github.com/kulshekhar/ts-jest/pull/44, checks coverage processor behavior if unexpected value delivered, especially with `allowJS` options in TSC who uses those configuration options.

Update test coverage for unexpected coverage values

---

package.json

Another, possible better option, would be to remove the typescript dependency all together.

Support dev versions of typescript.

---

.gitignore
src/preprocessor.ts
tests/__tests__/use-strict.spec.ts
tests/use-strict/Strict-valid.ts
tests/use-strict/Strict.ts
tests/use-strict/__tests__/Strict-valid.test.ts
tests/use-strict/__tests__/Strict.test.ts
tests/use-strict/package.json
tests/use-strict/tsconfig.json

Handle 'use strict'

---

.gitignore
.travis.yml
scripts/tests.js

I've added some small fixes to our test script in order to make it easier to maintain tests and avoid accidental checking published to npm project instead of current.
I've also removed allowed failure for node v7, because as for now it's realesed.

Test script improvement

---

package.json

Jest's current version is 18.1, and by specifying a version range of `~18.0.0` we preclude using that even though it's fine:
```
└── UNMET PEER DEPENDENCY jest@18.1.0
npm ERR! peer dep missing: jest@~18.0.0, required by ts-jest@18.0.0
npm ERR! code 1
```

Relax peer dependency version range on Jest

---

package.json
src/utils.ts
tests/__tests__/tsconfig-default.spec.ts
tests/__tests__/tsconfig-inline.spec.ts
tests/__tests__/tsconfig-string.spec.ts
tests/__ts-jest-mocks__/path.ts
tests/tsconfig-test/extends-tsconfig.json
tests/tsconfig-test/extends-with-overrides-tsconfig.json

More info: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

Add ability to resolve "extends" directive in tsconfig.json

---

AUTHORS
README.md
src/utils.ts
tests/__tests__/tsconfig-default.spec.ts

Related to #122 
It additionally adds myself to authors and includes tests and the note in the option section of Readme.
Plus, there was a bug (solved by this PR). The `convertCompilerOptionsFromJson` expects `config.module` to be an string in order to be parsed (like if it comes from a tsconfig.json). So that was returning undefined and not working:
```javascript
// Wrong
config.module = tsc.ModuleKind.CommonJS
...
tsc.convertCompilerOptionsFromJson(config, undefined).options.module // is undefined
```
```javascript
// Right
config.module = 'commonjs'
...
tsc.convertCompilerOptionsFromJson(config, undefined).options.module // is 5 (the value of tsc.ModuleKind.CommonJS)
```

Hardcode module commonjs

---

AUTHORS

I committed at work, so it used my work email, but I prefer to use my personal email for OSS activity :smile:

Update @maxdeviant's email address

---

package.json
src/preprocessor.ts
src/utils.ts
tests/__tests__/synthetic-default-imports.spec.ts
tests/no-synthetic-default/__tests__/module.test.ts
tests/no-synthetic-default/module.js
tests/no-synthetic-default/package.json
tests/no-synthetic-default/tsconfig.json
tests/synthetic-default/__tests__/module.test.ts
tests/synthetic-default/module.js
tests/synthetic-default/package.json
tests/synthetic-default/tsconfig.json

Hey, thanks for this lib. It has been super helpful :+1:
As discussed in #146, TypeScript doesn't implement default synthetic imports, so if you want to use those while targeting CommonJS (which Jest requires) you have to add an extra compile step, e.g. with Babel.
Usage of babel-jest as a post-ts-transform step was briefly discussed in #63, and that's what I have done in this PR.
Perf obviously takes a hit, but thanks to Jest's caching you rarely notice.

Support synthetic default imports

---

AUTHORS
package.json

As @blakeembrey pointed out here: https://github.com/kulshekhar/ts-jest/pull/180#issuecomment-297470047 babel-jest should not be a peer dependency because that would mean consumers of ts-jest would have to explicitly add it as dependency in their package.json, which would be a breaking change.

make babel-jest normal dependency

---

package.json

Fixes:
```
yarn v0.23.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "ts-jest@20.0.0" has incorrect peer dependency "typescript@^2.1.0".
```

fix: peer dependency against Typescript 2.x

---

package.json
src/preprocessor.ts
tests/__tests__/import.spec.ts
tests/__tests__/synthetic-default-imports.spec.ts
tests/__tests__/ts-compilation.spec.ts
tests/__tests__/ts-coverage-async.spec.ts
tests/__tests__/ts-coverage.spec.ts
tests/__tests__/ts-errors.spec.ts
tests/__tests__/tsconfig-comments.spec.ts
tests/__tests__/tsconfig-default.spec.ts
tests/__tests__/tsconfig-inline.spec.ts
tests/__tests__/tsconfig-string.spec.ts
tests/__tests__/tsx-compilation.spec.ts
tests/__tests__/tsx-errors.spec.ts
tests/__tests__/use-strict.spec.ts
tests/__tests__/watch.spec.ts

I removed a bunch of dead imports from all the tests.
the `import { } from 'jest';` ones - I'm reasonably sure they didn't do anything.
I removed dynamic requires for getTSJestConfig and mocked path via jest instead.
(This also neccesitated that getTSJestConfig needed a parameter because it wasn't of type `any` now, so I just gave it `null`)
Removed glob-all as it wasn't being used.
Changed some requires to es6 modules.
All tests still pass.

Code cleanups

---

.editorconfig
package.json
src/jest-types.ts
src/postprocess.ts
src/preprocessor.ts
tests/__tests__/get-cache-key.spec.ts
tslint.json
yarn.lock

To resolve #235 
Added 'json' moduleFileExtension, otherwise some tests fail.
I ported the babel-jest to our pipeline and started on something that might become a hook architecture at some point.
Would love to hear your thoughts.

New pipeline

---

src/postprocess.ts
src/preprocessor.ts
src/utils.ts
tests/__helpers__/runJest.ts
tests/__helpers__/runJestInWatchMode.ts
tests/__helpers__/utils.ts
tests/__mocks__/path.ts
tests/__tests__/jestconfig-json.spec.ts
tests/__tests__/jestconfig-package.spec.ts
tests/__tests__/tsconfig-comments.spec.ts
tests/__tests__/tsconfig-default.spec.ts
tests/__tests__/tsconfig-inline.spec.ts

Allows for better static analysis. I didn't remove all the requires, only the ones easily translatable into es6 modules. 
Resolves #225

Removed requires

---

README.md

https://github.com/kulshekhar/ts-jest/issues/250

added known limitation

---

package.json
src/utils.ts
tests/__tests__/tsconfig-comments.spec.ts
tests/tsconfig-test/allows-comments.json
tests/tsconfig-test/allows-comments2.json
tests/tsconfig-test/empty.ts
tests/tsconfig-test/tsconfig-module/empty.ts
yarn.lock

Aims at #245.
First of all - sorry for the confusion about what `tsc.readConfigFile` might simplify. Required some more things to apply to get this working. I've seen the usage of this function (also used it myself, of course) in several projects, and it worked without a hassle - otherwise, I wouldn't have suggested to head this ways. Seems my set of information got a bit ... malformed.
However, the results should not be that bad - the way config files are parsed and evaluated is quite close to how the typescript cli handles this, especially when following the `extends` key recursively. Note that the code is quite strict about errors: While the tsc API does not throw them, this code does, since they regularly would lead to curious behavior later on, e.g. when dealing with an obviously …

Use tsc to read config files, instead of separate tsconfig package

---

.travis.yml
yarn.lock

* Updates `yarn.lock` to account for `fs-extra@4` added in #267 
* Use ubuntu trusty instead of the default precise so the change doesn't catch us by surprise when travis changes the default ([travis trusty docs](https://docs.travis-ci.com/user/trusty-ci-environment/))
* Do not install `tslint` globally on travis, it's unnecessary as it's installed as a dependency

Update Travis CI environment, add fs-extra v4 to yarn.lock

---

README.md

Add introduce about "useBabelrc" and ES import

---

AUTHORS
README.md

Reverts kulshekhar/ts-jest#270
- The `Test code w/ ES (Webpack 2+) dynamic import` section seems unnecessary. It has nothing to do with ts-jest. 
- babelrc is spelled incorrectly
- The `Use customized .babalrc` section makes it seem that ts-jest uses babelrc by default. I don't think that's the case. @GeeWee can you confirm one way or another?
The author list should also be updated to include @whitetrefoil
closes #265

Rewrite 'useBabelrc' documentation 

---

AUTHORS
README.md

Without `json` in `moduleFileExtensions`, I was getting error `Cannot find module './package' from 'index.js`
https://github.com/facebook/jest/issues/1371

Update docs to include json in `moduleFileExtensions`

---

AUTHORS
src/preprocessor.ts
tests/__tests__/get-cache-key.spec.ts

Transform cache invalidation for coverage seems to implicitly rely on instrumentation changing some value in tsconfig. Besides making the invalidation more explicit, since the last value passed to getCacheKey is an options bag, ts-jest can insulate itself from new transform options being added in the future that should also bust the cache by just stringifying the object. I'm trying to get a change into jest that adds mapCoverage to the options here, for example.

explicitly invalidate cache key when transform options change

---

AUTHORS
package.json
yarn.lock

Looks like this was added in https://github.com/kulshekhar/ts-jest/commit/7e927e3d529a00c29dc87769b9da3ad8d7c7146e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R59 - I think it's reasonable to assume that this is a bug (I've done this by accident many times and [automated a check](https://github.com/orta/danger-plugin-yarn/blob/master/src/index.ts#L179))
I was getting build failures in another project due to this: https://travis-ci.org/danger/danger-js/jobs/261328625#L938 - maybe because of different TS versions

Move @types/babel to dev dependencies

---

src/index.ts

This change allows source-map-support to use the default value for `emptyCacheBetweenOperations` (`false`) to improve the performance of ts-jest.
Thanks to @hermanbanken for [pointing out this issue](https://github.com/kulshekhar/ts-jest/issues/259#issuecomment-320227209) in #259

Let sourcemaps be cached

---

package.json
src/preprocessor.ts
src/utils.ts
tests/__tests__/tsconfig-default.spec.ts
tests/__tests__/tsconfig-inline.spec.ts
tests/__tests__/tsconfig-string.spec.ts

Fixes #299 
This PR also changes some related tests. The tests for the configuration object were doing an exact match to check that the actual object is exactly equal to the expected object.
These tests have been updated to assert that the expected object is a subset of the actual object. This is because the actual object will now always have `inlineSources` and `inlineSourceMap` set to true.

Always set inlineSources and inlineSourceMap to true

---

README.md
collaborator-guidelines.md

fixes #273 
Feel free to add any comment.

docs: unify package name styling

---

README.md

ts-jest README:
```json
{
"jest": {
"transform": {
".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
},
"testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
"moduleFileExtensions": [
"ts",
"tsx",
"js",
"json"
]
}
}
```
Jest documentation ([1](http://facebook.github.io/jest/docs/en/getting-started.html#using-typescript)) ([2](https://github.com/facebook/jest#using-typescript)):
```json
{
"jest": {
"transform": {
"^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
},
"testRegex": "(/__tests__/.*|\\.(test|spec))\\.(tsx?|jsx?)$",
"moduleFileExtensions": [
"ts",
"tsx",
"js",
"json",
"jsx"
]
}
}
```
- moduleFileExtensions: jsx missing in ts-jest README
- transform are different
- testRegex are different
Which one is considered to be "canonical"/the official one? …

Improve usage

---

README.md

Adding info about limitations in debugger statements in README

---

README.md
package.json
tests/__tests__/get-cache-key.spec.ts
tests/__tests__/ts-coverage-async.spec.ts
tests/__tests__/ts-coverage.spec.ts
tests/button/package.json
tests/deprecated-tsconfig/package.json
tests/dynamic-imports/jest.allowdefaultimports.json
tests/dynamic-imports/package.json
tests/hoist-errors/package.json
tests/hoist-test/package.json
tests/imports-test/package.json
tests/jestconfig-test/jest.json
tests/no-synthetic-default/package.json
tests/simple-async/package.json
tests/simple-long-path/package.json
tests/simple/package.json
tests/skip-babelrc/package.json
tests/synthetic-default/package.json
tests/use-babelrc/package.json
tests/use-strict/package.json
tests/watch-test/package.json

Following #310
- `".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"`
should be `"^.+\\.tsx?$"` see [1](https://github.com/facebook/jest/blob/v20.0.4/packages/jest-config/src/constants.js#L14), [2](https://github.com/facebook/jest/tree/master/packages/babel-jest#setup), [3](https://github.com/facebook/jest/blob/de74b38aff9f0a91dcdaf5986d2a6f963b78cfdf/examples/typescript/package.json#L18)
- `"testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$"`
should be `"(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$"` see [1](https://github.com/facebook/jest/blob/de74b38aff9f0a91dcdaf5986d2a6f963b78cfdf/packages/jest-config/src/valid_config.js#L84), [2](http://facebook.github.io/jest/docs/en/configuration.html#testregex-string)
<br>
Is `"^.+\\.tsx?$"` that different from …

Use "canonical" Jest configuration

---

package.json

Greenkeeper had updated this (#326) but `yarn.lock` didn't get updated properly. Reverting this to
- hopefully have greenkeeper send in a PR along with the yarn.lock updates
- test the new setup (#329) for this

Revert yargs to 8.0.1

---

package.json
src/utils.ts
tests/__tests__/synthetic-default-imports.spec.ts

Mimic jest behaviour to find `package.json` (and his config inside it)
See
https://github.com/facebook/jest/blob/d62a7e0edfec556758e1c0e23158e4ce4ac84e91/packages/jest-runtime/src/cli/index.js#L60-L68
https://github.com/facebook/jest/blob/e04e45102b3ebe486462d45db656f9b47f0e70e1/packages/jest-config/src/index.js#L18-L26  
resolved #347

Set the start dir of looking for tsconfig to process.cwd()

---

AUTHORS
package.json
src/postprocess.ts

If the user specifies a babel config for *ts-jest* in `package.json`, but only includes a `presets` and not `plugins`, https://github.com/kulshekhar/ts-jest/blob/3039ef39075453b948c891f50e4a4d69b95f4cfc/src/postprocess.ts#L69 will assign `undefined` to `plugins`.  In the next line, the extra plugin (`transform-es2015-modules-commonjs`) is `push`ed into this variable, which will obviously fail if it's not an array.

Fix postprocess bug when babel config is supplied with no plugins

---

AUTHORS
README.md
index.js
package.json
src/install.ts
src/preprocessor.ts
tests/__tests__/transpile-if-ts.spec.ts
tests/jestconfig-test/jest.json

This way, the `"ts-jest"` package name can be used as Jest transform, instead of specifying the path to preprocessor.js.
The latter did not work when the ts-jest package had been hoisted to a parent folder (for example by lerna).
Fixes https://github.com/kulshekhar/ts-jest/issues/361

Change the package entry point to preprocessor.js itself

---

tests/__tests__/tsx-errors.spec.ts
tests/button/__tests__/Button.test.tsx
yarn.lock

This replaces the use of test-renderer with shallow renderer in a test that caused a test to fail with React 16 and Node 8 (#334)
While this helps us avoid skipping tests, it isn't a real fix for that issue. However, it probably indicates that the issue lies somewhere in the test-renderer.

Use shallow renderer in tsx test to avoid skipping it with node8/react16

---

AUTHORS
package.json
src/postprocess.ts
tests/__tests__/postprocess.spec.ts

Previously, each import in a test suite would add an extra `'transform-es2015-modules-commonjs'` transform to the babel config.
cc @lemonmade - this was adding ~27 seconds to our test startup.

Don't accumulate commonjs module transforms

---

AUTHORS
package.json

It's not used
Not sure why it was added in #109

Remove jest-util as dependency

---

package.json
src/jest-types.ts
src/preprocessor.ts

Following the discussion in #406 
https://github.com/kulshekhar/ts-jest/issues/406#issuecomment-354708580
This PR removes some caching that ts-jest does. Given that we have the `getCacheKey` function that jest can use to determine whether to cache something or not, there seems no reason to continue caching internally.

Disable internal caching

---

AUTHORS
README.md
package.json
src/jest-types.ts
src/preprocessor.ts
src/utils.ts
tests/__tests__/ts-diagnostics.spec.ts
tests/ts-diagnostics/Hello.ts
tests/ts-diagnostics/__tests__/Hello.test.ts
tests/ts-diagnostics/package.json
tests/ts-diagnostics/tsconfig.json

By creating a `program` we are enabled to run diagnostics on typescipt files in order to emit semantic errors. For the time being I only used one of the many methods this one is `getPreEmitDiagnostics`
This enables syntactic & semantic TypeScript error reporting

feat: add option to run TypeScript diagnostics

---

AUTHORS
README.md

As far as I know `useBabelrc` has to be set to true so that ts-jest uses the `.babelrc`. Since the react-native section declares a `.babelrc` it should also show that the option needs to be enabled.

Include useBabelrc in react-native example

---

AUTHORS
package.json
src/preprocessor.ts
src/transpile-if-ts.ts
src/utils.ts
tests/__tests__/jest-projects.spec.ts
tests/jest-projects/package.json
tests/jest-projects/packages/child/Hello.ts
tests/jest-projects/packages/child/__test__/index.test.ts
tests/jest-projects/packages/child/custom-tsconfig.json
tests/jest-projects/packages/child/package.json

fix #422
in order to support jest multi-project, need to reference `jestConfig.rootDir`.
Find tsconfig based on rootDir.
---
- multi-project detail
- news: https://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html
- options: https://facebook.github.io/jest/docs/en/configuration.html#projects-array-string-projectconfig

support for jest multi-projects

---

src/utils.ts

Create a new object when logging the initial config state

---

src/jest-types.ts

I recognize we have some missing types in FullJestConfig. This PR is to keep it in sync with types definition in Jest at https://github.com/facebook/jest/blob/master/types/Config.js

Update types for FullJestConfig to be in sync with types in Jest

---

package.json
src/jest-types.ts
src/preprocessor.ts
tests/__tests__/disable-sourcemap-support.spec.ts

Allow disabling sourcemap support

---

AUTHORS
README.md
package.json
src/jest-types.ts
src/preprocessor.ts

As discussed in #454 there is a problem with coverage on decorators when emitDecoratorMetadata is enabled. This is kind of a hack to fix this until something better is implemented in tsc/jest/istanbul. There are two options. First you can set a configuration option ignoreCoverageForAllDecorators to true and it will ignore all decorators (and possible something else). The second option is to add /* istanbul ignore decorate */ right after the decorator like this
`@Decorator /* istanbul ignore decorate */`

fix for decorator coverage

---

package.json
yarn.lock

As mentioned in #506, 'source-map-support' is required in [install.ts](https://github.com/kulshekhar/ts-jest/blob/970d4a83926ba96eae7b9a5ac67b5f0d636066c3/src/install.ts#L1), but does not explicitly appear in package.json.

Add 'source-map-support' to package.json dependencies

---

package.json
src/transpiler.ts

It is necessary to supply realpath to language host so that typescript could follow symlinks as it supposed to be.

Add realpath to language host

---

src/utils.ts
tests/__tests__/use-config-from-node-modules.spec.ts
tests/use-config-from-node-modules/Hello.ts
tests/use-config-from-node-modules/__tests__/Hello.test.ts
tests/use-config-from-node-modules/package.json
tests/use-config-from-node-modules/tsconfig.json

* Use Jest rootDir in parseJsonConfigFileContent as basePath
* Add test for config from node_modules
Fix issue https://github.com/kulshekhar/ts-jest/issues/536

Fix problem with tsconfig from node_modules (Issue #536)

---

src/jest-types.ts
src/postprocess.ts

- Add new types of Jest 23
- Change interface name to be more relevant (`FullJestProjectConfig`) to the one in Jest repo because we refer to their `ProjectConfig`

Add new types from Jest 23

---

AUTHORS
src/utils.ts
tests/__tests__/tsconfig-default.spec.ts

In the weird case you'd have such a directory structure:
```
src/
...
other-src/
tsconfig.json
tsconfig.json
```
and `jest.globals` would be the same for both directories, the second call to `getTSConfig` will return the same as the other one, because `rootDir` is ignored in the cache key resolver for `getTSConfig`.
I've also added the reset of `memoized` cache for that function before each test, as it could land to weird results in some cases (passing but shouldn't or even the opposite because of cached data between tests)

[FIX] cache key resolver for getTSConfig

---

package.json

This ts-jest works fine with TypeScript 3 also, so I did change the version mask in peerDependencies to support all TypeScript 2 and 3 versions.

Add TypeScript ^3.0.0 as supported peer dependencies

---

README.md

There are many issues about how to set up paths/moduleNameMapper. I think they will keep arising because the docs are not clear enough.

Add more details on using module name mapper

---

package.json

Looks like `cpx`, `jest-config`, `pkg-dir` and `yargs` are only used for build and tests. They have quite a lot of transitive deps too so moving them to devDependencies would result on smaller node_modules for users.

Move dev only deps to devDependencies.

---

package.json
src/utils/imports.ts

this needs a test to be run outside of ts-jest root path, I'm adding one now, but this can be merged first to address the issue. I've tested using npm pack (and not npm link 😖) in the repository linked in https://github.com/kulshekhar/ts-jest/issues/651#issuecomment-410204956

[HOTFIX] wrong error message

---

src/utils/get-ts-config.ts
tests/__tests__/tsconfig-default.spec.ts

This is a proposed fix for issue #691.
As described in that issue, TypeScript doesn't require the user to create a `tsconfig.json` file anymore and in fact does not recommend it in their getting started section. I actually completely forgot about it because I was using Parcel, a zero-config bundler so it handled config options.
So I saw two options:
1. Force `ts-jest` to use an empty config object if no `tsconfig.json` is found.
2. Tell the user in the documentation that they must supply one to use `ts-jest`.
Since `ts-jest` actually works with an empty config object, I felt it was cleaner to simply take the first option rather than ask the user to put in a dummy file which is not needed by `typescript` or `ts-jest`.
This PR does that. It also removes a test which expects to throw an …

Fix for #691

---

src/transformers/README.md
src/transformers/hoist-jest.ts
src/transformers/index.ts

This doesn't change the generate code, but as @cspotcode pointed me out, this creates a mutable node before actually mutating it.
Ti doesn't change anything in the generated code (of what I've tested and what is in the e2e tests), but cloning readonly stuff before mutating is always advised right 🤣?
There is also a fix for the transformer boilerplate code anyway.

[beta] Use the proper way of mutating a node in a transformer

---

package.json

- `jest` brings `babel-jest`, so we don't want `babel-jest` in the peers
- users may want to use `ttypescript` instead of `typescript`, or even another typescript compiler, so `typescript` shouldn't be in peer deps.
Now yarn or npm will warn only if `jest` is not installed or if version isn't in our compatible range.
TSJest will warn anyway if an installed package's version does not verify our compatible range for those packages (unless it is not `require()`d):
https://github.com/kulshekhar/ts-jest/blob/e70d11c0f66c4853153f5ccfcb2ec879be2b58de/src/util/version-checkers.ts#L9-L15

[beta] updates peers & merge master

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts
src/util/messages.ts
tsconfig.build.json
tsconfig.json

Given a jest config with:
```js
{
// [...]
transform: {
'\\.(js|ts)$': 'ts-jest',
}
}
```
and a `tsconfig.json` where `allowJs` compiler option is missing or set to `false`, `ts-jest` will be given `.js` files even tho it's not supposed to process them. TypeScript would bail in that case.
This PR make it so that input js code from `.js` files is returned unmodified (in the above described case), and a warning message is shown.
This kinda fixes confusions made such as in #721

[beta] warns the user if jest config transform matches js files without allowJs in tsconfig

---

src/cli/config/init.ts
src/cli/config/migrate.ts
src/cli/help.ts
src/cli/index.ts
src/compiler.ts
src/config/config-set.ts
src/index.ts
src/transformers/hoist-jest.ts
src/transformers/index.ts
src/ts-jest-transformer.ts
src/types.ts
src/util/backports.ts
src/util/get-package-version.ts
src/util/hacks.ts
src/util/importer.ts
src/util/json.ts
src/util/jsonable-value.ts
src/util/logger.ts
src/util/memoize.ts
src/util/messages.ts
src/util/normalize-slashes.ts
src/util/sha1.ts
src/util/ts-error.ts
src/util/version-checkers.ts
tsconfig.build.json

Closes #745
FYI reviewers all changes are about adding the `@internal` comment and changing the tsconfig so that declaration files are emitted.
Some files look like more changes, but it's just some re-ordering of methods depending on their modifiers which has been done automatically by the linter. Some other changes might be the refactoring from `export {...}` to individual exports as the `@internal` does not work within export maps.

Emit declaration files, filtering out internals

---

src/config/config-set.ts
src/types.ts
src/util/importer.spec.ts
src/util/importer.ts
src/util/messages.ts

The importer is responsible of importing and patching modules with configurable fallbacks. If one is missing, it goes to the next one. Previously if a module existed but was failing when loading it with `require`, it'd report as missing instead of failing. Now it bubbles the error correctly.

Fixes wrong error message when a module exists but fails loading

---

package.json

using `semver.coerce` here https://github.com/kulshekhar/ts-jest/blob/v23.10.2/src/util/hacks.ts#L20 
and we have it as 5.x in package.json, but `.coerce` was introduced in semver v5.5.0 https://github.com/npm/node-semver/commit/e7092b4040360f1b24c1119defe45ed3b38a77ef , so need to be more explicit about semver version
cc @huafu

use semver >= v5.5.0 so semver.coerce is there

---

CHANGELOG.md
package-lock.json
package.json

* **cache:** adds project's dep versions to cache key ([6cacbea](https://github.com/kulshekhar/ts-jest/commit/6cacbea)), closes [#785](https://github.com/kulshekhar/ts-jest/issues/785)
* **cli:** change options to better reflect the new presets ([68abcfb](https://github.com/kulshekhar/ts-jest/commit/68abcfb))
* **helpers:** deprecate import from ts-jest, now ts-jest/utils ([33ff29f](https://github.com/kulshekhar/ts-jest/commit/33ff29f)), closes [#782](https://github.com/kulshekhar/ts-jest/issues/782)
* **typings:** typo in presets definition file ([53767ab](https://github.com/kulshekhar/ts-jest/commit/53767ab))
* **typings:** wrong import in preset typings + test ([94dc4e7](https://github.com/kulshekhar/ts-jest/commit/94dc4e7))

chore(release): 23.10.4

---

scripts/lib/bundle.js

globIgnore now requires the 'absolute' option to be specified.

fix: update call to globIgnore (#1002)

---

docs/user/config/index.md
docs/user/config/packageJson.md
src/__helpers__/fakers.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/types.ts

Addresses issues #823 and #852

feat(config): specify package.json location (#823)

---

e2e/__cases__/test-helpers/pass.spec.ts
e2e/__cases__/test-helpers/to-mock.ts
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-typescript-2-7/package-lock.json
e2e/__templates__/with-typescript-2-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
e2e/__tests__/__snapshots__/test-helpers.test.ts.snap
package-lock.json
package.json
src/config/config-set.spec.ts
src/ts-jest-transformer.spec.ts
src/util/testing.ts

Also add a test for mocking classes.
I'm a bit unsure about the changes in `ts-jest-transformer.spec.ts` - it seems like the typings for `configsFor` changed and are expecting something quite different than what the mocks are returning.  Having to do "as unknown" isn't good - but the tests pass?
Fixes #991

Bump @types/jest to 24 and fix the associated typings and tests

---

src/compiler.ts

I was having problems with ts-jest failing to compile in my `pnpm` monorepo with weird errors because it apparently wasn't finding dependencies of `@types` packages, despite the fact that `tsc` works fine. This change fixes it.
The reason is that `pnpm` symlinks packages like this:
```
> ls -l node_modules/@types/
express -> ../../../../node_modules/.registry/@types/express/4.17.0/node_modules/@types/express
```
The transitive dependencies are not in the consuming package's `node_modules` or its parents, instead they are in `../../../node_modules/.registry/@types/express/4.17.0/node_modules/`, so it's necessary to resolve the symlink to its  referent in order to find the  dependencies. When ts-jest doesn't implement this resolution, TypeScript assumes all the files are not symlinks and …

fix: #825 handle symlinked modules (ala pnpm) correctly

---

e2e/__cases__/composite/foo.spec.ts
e2e/__cases__/composite/tsconfig.json
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__tests__/__snapshots__/test-helpers.test.ts.snap
e2e/__tests__/composite.test.ts
src/config/config-set.ts

fix: handle tsBuildInfoFile option

---

src/index.ts

These should be carried into the `index.d.ts` by tsc, and the ideally IDEs should avoid them when more suitable non-deprecated imports of the same name can be found.
Some IDEs will also mark usages of `@deprecated` identifiers w/ a strikethrough, making it easier & quicker to discover that they're deprecated :D

chore(index): add `@deprecated` jsdoc to deprecated utils

---

src/compiler.ts

close #1226
thanks @jaysoo and @Floppy012 for fix suggestion and explanation.

fix(compiler): pass filename to sha function instead of file extension

---

e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-typescript-2-7/package-lock.json
e2e/__templates__/with-typescript-2-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
package-lock.json
package.json
src/cli/cli.spec.ts
src/util/version-checkers.spec.ts
src/util/version-checkers.ts

Jest has released version 25 under the `next` dist-tag:
- https://www.npmjs.com/package/jest/v/25.0.0
- https://github.com/facebook/jest/pull/8862
The maintainer promised no more user facing breaking changes planned
https://github.com/facebook/jest/issues/8956#issuecomment-531671339
I've tested the new version in my local branch and figured out only these files need to be updated to support Jest 25 (Not sure if the updated tests should be included in this PR):
- Update `peerDependencies` version range to include v25
- Update `ExpectedVersions` to allow new versions
- Remove `async` `describe` blocks in the tests to eliminate warnings from https://github.com/facebook/jest/pull/7852

feat: support Jest 25

---

package-lock.json
package.json
src/cli/index.ts
src/shims.d.ts

Upgraded yargs-parser to v16 and moved to using types from DefinitelyTyped (Using v15 since v16 is not available but looks like API-wise nothing has changed since 15).
Closes https://github.com/kulshekhar/ts-jest/issues/1374

chore: upgrade yargs parser to v16

---

.travis.yml
appveyor.yml
e2e/__monorepos__/simple/dependency/imported-module.ts
e2e/__monorepos__/simple/dependency/index.ts
e2e/__monorepos__/simple/dependency/package.json
e2e/__monorepos__/simple/dependency/tsconfig.json
e2e/__monorepos__/simple/with-dependency/index.ts
e2e/__monorepos__/simple/with-dependency/package-lock.json
e2e/__monorepos__/simple/with-dependency/package.json
e2e/__monorepos__/simple/with-dependency/test/index.spec.ts
e2e/__monorepos__/simple/with-dependency/tsconfig.json
package.json
scripts/test-external-project.js
src/compiler.ts

Fixes #1294 and possibly some of #1343
Most of this PR was derived from the implementation in ts-loader and a bunch of manual debugging. See #1381 for another possible solution.
Any comments are appreciated, especially in regards to testing. To make a meaningful E2E test we probably need a mocked package written in TS.

fix: allow transformation of typescript files in node_modules

---

.travis.yml
appveyor.yml
package-lock.json
package.json

- Move unit tests form AppVeyor Windows to Travis Windows for node 8
- Set `husky` version at 3.x because 4.x isn't compatible with node 8
Related to #812

chore(e2e): move unit test from AppVeyor Windows to Travis Windows

---

CONTRIBUTING.md
README.md
docs/index.md
docs/user/config/diagnostics.md

**What**
Fixing broken slack links and some minor typos in documentation
**Discussion**
https://ts-jest.slack.com/archives/CC6B0LYJD/p1582074011015000
**Test Steps**
1. Review documentation changes
2. Test slack bit.ly link: `https://bit.ly/3bRHFPQ`

docs:fix-doc-typos-and-links Fix slack links and typos

---

CHANGELOG.md
package.json

@kulshekhar I saw you forgot to adjust version `package.json` for release 25.2.1 so this PR is to adjust it, and also correct changelog for releases of v24 and v25.
Our command to generate changelog depends on our commit history so it's a bit messy with v24 and v25 changelog so I had to manually modify it. Just a note to let you know if you generate the changelog by our command.
I think when merging, better we use squash and merge to keep the commit history clean to be easy to generate changelog.

fix(docs): adjust changelog, correct version in package.json

---

e2e/__monorepos__/simple/with-dependency/package.json
package-lock.json
package.json
src/__mocks__/tsconfig.json
src/compiler/__snapshots__/language-service.spec.ts.snap
src/compiler/__snapshots__/program.spec.ts.snap
src/compiler/__snapshots__/transpile-module.spec.ts.snap
src/compiler/instance.ts
src/compiler/language-service.spec.ts
src/compiler/language-service.ts
src/compiler/program.spec.ts
src/compiler/program.ts
src/compiler/transpile-module.spec.ts
src/compiler/transpile-module.ts
src/transformers/hoist-jest.ts
src/types.ts
tsconfig.json

Expose internal ts `Program` via `ConfigSet.tsCompiler.program` 
closes #1146

feat(compiler): expose internal ts Program via ConfigSet tsCompiler

---

e2e/__tests__/__snapshots__/compiler-host.test.ts.snap
e2e/__tests__/__snapshots__/diagnostics.test.ts.snap
e2e/__tests__/__snapshots__/test-helpers.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/amd.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/commonjs.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/es2015.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/esnext.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/none.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/system.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/umd.test.ts.snap
src/compiler/__snapshots__/language-service.spec.ts.snap
src/compiler/__snapshots__/program.spec.ts.snap
src/compiler/__snapshots__/transpile-module.spec.ts.snap
src/compiler/program.spec.ts
src/config/config-set.spec.ts
src/util/messages.ts
src/util/ts-error.ts

chore: improve diagnostics message

---

src/compiler/language-service.ts

Just a slight performance improvement but better than nothing.

chore(compiler): improve performance for language service with project version

---

src/config/config-set.spec.ts
src/config/config-set.ts

fix(config): set default outDir to `$$ts-jest` when `allowJs` is enabled without `outDir`

---

src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.ts
src/types.ts

- Mark some codes as internal
- Remove unused codes
- Add typings
- `checkJsFile` doesn't need to check if a file is type definition type

chore: mark some codes as internal

---

e2e/__tests__/diagnostics.test.ts
src/compiler/program.spec.ts

Fix local unit tests for program
local unit tests pass
CI pass
**N.A.**

chore: fix program unit tests fail for local machine

---

e2e/__cases__/diagnostics/main.spec.ts
e2e/__cases__/diagnostics/main.ts
e2e/__tests__/__snapshots__/diagnostics.test.ts.snap
e2e/__tests__/diagnostics.test.ts
src/compiler/compiler-utils.spec.ts
src/compiler/compiler-utils.ts
src/compiler/language-service.ts
src/compiler/program.ts
src/types.ts

In #1483, we introduced caching imported modules for test files and use that cache to do type checking for test files once one of the imported modules' contents changes. 
However, this causes a bug that when running tests with cache and one of the imported modules' contents changes, language service sometimes doesn't have the information of the test file to do type checking which then throws error `Cannot find source file ....`.
close #1506 
- Added e2e tests to cover #1506 and #1390 
- Green CI
**N.A.**

fix(compiler): make sure `LanguageService` updated with test file information before getting diagnostics for test file

---

e2e/__tests__/__snapshots__/diagnostics.test.ts.snap
src/__helpers__/fakers.ts
src/compiler/compiler-utils.ts
src/compiler/language-service.spec.ts
src/compiler/language-service.ts
src/compiler/program.spec.ts
src/compiler/program.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Jest config string doesn't contain the correct value for `testRegex` therefore `micromatch` in compiler failed to validate file name against this value, see related issue reported for `jest` team to handle: https://github.com/facebook/jest/issues/9778. 
This PR switches to use original jest config object to get the correct value for `testRegex`, close #1509 
Green CI
**N.A.**

fix(config): use original jest config object

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/regression.md

Correct set debug log instruction for Bug and Regression templates. On Windows, `set TS_JEST_LOG="ts-jest.log"` doesn't work but only `set TS_JEST_LOG=ts-jest.log` works. 
For Linux/MacOS both `TS_JEST_LOG="ts-jest.log"` and `TS_JEST_LOG=ts-jest.log` work.
Close #1532 
**N.A.**
**N.A.**

chore: correct set debug log in Bug/Regression template

---

src/__helpers__/fakers.ts
src/compiler/__snapshots__/language-service.spec.ts.snap
src/compiler/__snapshots__/transpiler.spec.ts.snap
src/compiler/instance.ts
src/compiler/language-service.spec.ts
src/compiler/language-service.ts
src/compiler/program.ts
src/compiler/transpiler.spec.ts
src/compiler/transpiler.ts
src/config/config-set.ts

- Rename some methods to be easier to understand what they do
- Rename `transpile-module` to `transpiler`
Green CI
**N.A.**

chore: rename some files and methods in compiler area

---

src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/constants.ts

Jest config which is passed to transformer doesn’t always contain the correct value of `testRegex`, see https://github.com/facebook/jest/issues/9778. Since we rely on this, we should add a filter to make sure we get out the patterns which are `RegExp` instance or type `string`. 
Also we add a fallback to default `testMatch` value, see https://jestjs.io/docs/en/configuration#testmatch-arraystring in case no patterns valid by the check above.
Fix #1552 
- Added unit tests.
- Green CI
**N.A.**

fix(config): verify testMatchPatterns contain RegExp instance or string

---

docs/user/config/index.md
docs/user/config/tsConfig.md
src/config/config-set.spec.ts
src/config/config-set.ts
src/types.ts

Fixes #1564 
Added `tsconfig` scenario to existing relevant test.

feat: add tsconfig alias to tsConfig option

---

src/compiler/compiler-utils.ts
src/compiler/instance.ts
src/compiler/language-service.ts
src/compiler/transpiler.ts
src/types.ts

`Maps` are about twice as fast for larger data sets in Chrome 80, very much likely this applies to Node as well: https://stackoverflow.com/a/55711780/1850276
Green CI
**N.A.**

chore: use Map for compiler memory cache

---

.npmignore
CHANGELOG.md

One of the preparation steps for release **v25.5.0-beta.0**
I also added `.idea` to `.npmignore` so when we run `npm pack`, it won't pack `.idea` folder into `tgz` file.
Green CI
**N.A.**

chore: update CHANGELOG for release v25.5.0-beta.0

---

.github/workflows/release-and-publish.yml
README.md

Added release-and-publish.yml file which triggers when ever a tag is
created or pushed. Following actions are done:
* create release for tag pushed
* publish package to npm
closes: https://github.com/kulshekhar/ts-jest/issues/664
1. Verified that actions are getting triggered for creation of tag. Those actions can be viewed at my [fork actions section](https://github.com/anshulguleria/ts-jest/actions?query=workflow%3Arelease-and-publish).
2. Publish is failing as I don't have required `NPM_TOKEN` and authorization to publish. This needs to be tested once this change gets merged.

Adds workflow for release and publish

---

src/compiler/instance.ts
src/compiler/language-service.ts
src/compiler/transpiler.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

The variable `input` in `readTsConfig` method of `config-set.ts` isn't in used anywhere so this PR is to remove it. I also rename the getter `typescript` to `parsedTsConfig`, make it clearer to understand.
The removing of this variable shouldn't cause any bugs though. Green CI
**N.A.**

chore: improve codes for config-set.ts

---

docs/user/config/index.md
e2e/__helpers__/test-case/runtime.ts
package-lock.json
src/index.ts

- Define `ts-jest` on jest `ConfigGlobals` interface to ultilize TypeScript declaration merging.
- Adjust docs to instruct users how to do it.
Close #1588 , thanks @G-Rath for suggested solution 👍 
Build `ts-jest` then copy `dist` folder to `node_modules/ts-jest/dist` of an example project and follow the docs. Check if your IDE gives the suggestion of `ts-jest` config options.
**N.A.**

feat(config): define 'ts-jest' on ConfigGlobals interface in @jest/types

---

CHANGELOG.md
docs/user/config/isolatedModules.md
e2e/__external-repos__/custom-typings/tsconfig.json
src/config/config-set.spec.ts
src/config/config-set.ts

- Revert #1562 
- Add doc to instruct how to boost performance and caveats
Close #1604 
Close #1607 
Close #1608
Green CI
**N.A.**

fix(config): don't set include property value of tsconfig to empty array

---

src/compiler/language-service.ts

Close #1639 
Not sure how to test this. But from code perspective, using `!` operator is wrong.
**N.A.**

fix(compiler): return undefined for getScriptVersion

---

e2e/__external-repos__/custom-typings/package.json
e2e/__external-repos__/custom-typings/yarn.lock
e2e/__external-repos__/simple-project-references/package.json
e2e/__external-repos__/simple-project-references/yarn.lock
e2e/__external-repos__/simple/dependency/package.json
e2e/__external-repos__/simple/with-dependency/package.json
e2e/__external-repos__/simple/with-dependency/yarn.lock
e2e/__external-repos__/yarn-workspace-composite/package.json
e2e/__external-repos__/yarn-workspace-composite/yarn.lock
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7-string-config/package-lock.json
e2e/__templates__/with-babel-7-string-config/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
e2e/__tests__/__snapshots__/source-map.test.ts.snap
package-lock.json
package.json
src/util/memoize.ts

- Upgrade `typescript` to **3.9** for project dependency, e2e templates, external repos
- Add a workaround in `memoize.ts` for a breaking change, see https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/
```
Type Parameters That Extend any No Longer Act as any
```
- Update snapshots
Green CI
**N.A.**

feat: support TypeScript 3.9

---

src/config/create-jest-preset.spec.ts
src/config/create-jest-preset.ts

Since `jest` exposes typings for config, we should use it so our typings always follow correctly what `jest` expects. 
This PR is to use `InitialOptions` to pick out some properties of jest config we need for our `TsJestPresets` type.
Green CI
**N.A.**

chore(dev-infra): create TsJestPresets typings based on Jest typings

---

.eslintrc.js
e2e/__cases__/hoisting/enable-automock/enable-automock.spec.ts
e2e/__tests__/__snapshots__/hoisting.test.ts.snap
e2e/__tests__/hoisting.test.ts
src/compiler/compiler-utils.ts

TS 3.9 introduces [ts-expect-error](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/#ts-expect-error-comments) which helps to prevent using `ts-ignore` inproperly.
This PR is to enable that rule in eslint.
Green CI
**N.A.**

chore(dev-infra): enable rule @typescript-eslint/prefer-ts-expect-error

---

e2e/__tests__/__snapshots__/logger.test.ts.snap
e2e/__tests__/logger.test.ts
e2e/jest.config.js
jest-base.js
jest.config.js
src/config/config-set.spec.ts
src/config/config-set.ts
src/util/messages.ts
src/util/version-checkers.ts
tsconfig.json
tsconfig.spec.json

Often I see `ts-jest` users run into the problem and turned out that ones set the `target` version in their `tsconfig` to be incompatible with their NodeJs version. This can result in some features of TypeScript when transpiling to `commonjs` aren't supported by a specific NodeJs version.
This PR is to add a warning message for NodeJs 10/12 users that they should use recommended `target` by TypeScript team at https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
Added unit test and e2e test. Green CI
- Created a base jest config `jest-base.js` and e2e test as well as unit test config extend from it.
- Created a `tsconfig.spec.json` to use for unit test/e2e test to speed up CI following the doc https://kulshekhar.github.io/ts-jest/user/config/isolatedModules#example-1

feat(config): show warning message for nodejs ts target version mismatch

---

e2e/__external-repos__/simple-project-references/jest.config.js
e2e/__external-repos__/simple-project-references/src/__tests__/divide.ts
e2e/__external-repos__/simple-project-references/src/__tests__/multiply.ts
e2e/__external-repos__/simple-project-references/src/__tests__/subtract.ts
e2e/__external-repos__/simple-project-references/src/math/divide.ts
e2e/__external-repos__/simple-project-references/src/nested/src/multiply.ts
e2e/__external-repos__/simple-project-references/src/nested/subtract.ts
e2e/__external-repos__/simple-project-references/tsconfig-base.json
src/config/paths-to-module-name-mapper.spec.ts
src/config/paths-to-module-name-mapper.ts
src/util/messages.ts

feat(config): add support for multiple paths in module name mapper

---

docs/user/config/astTransformers.md
docs/user/config/babelConfig.md
docs/user/config/index.md
docs/user/config/isolatedModules.md

The config documentation is missing the option `astTransformers`. This PR is to provide the documentation for it.
Wait for deployment of github page and check :)
For some reasons, markdown doesn't show correctly styling on doc page when using `json5` so I adjusted to `js` to get proper styling.

docs: add missing `astTransformers` config option documentation

---

e2e/__helpers__/test-case/types.ts
e2e/__tests__/__snapshots__/source-map.test.ts.snap
e2e/__tests__/source-map.test.ts
src/compiler/instance.ts
src/config/config-set.ts

Fixes #1718 
Added e2e test
**N.A.**

fix(compiler): generate source map correctly when tsconfig `mapRoot` is set

---

src/__helpers__/fakers.ts
src/compiler/language-service.spec.ts
src/compiler/language-service.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts

#1784 introduced the usage `resolveModuleNames` API from `LanguageService`. I noticed that `resolveModuleNames` API can have a cache called `ModuleResolutionCache` so I went ahead and tried out. The result is amazing:
- Before #1784 and after #1784: the performance is more less similar, sometimes #1784 makes performance even worse.
- With this PR: the performance is even better than before #1784 and after #1784 
**Some figures**
Testing against my company's project which has 2k+ test files as well as the repo source has 2k+ files.
After #1784 
```
PASS  src/__tests__/pulse-items/pulse-items-filter.helper.spec.ts (5.736s)
PASS  src/__tests__/hybrid-apps/widget-card-settings.handler.spec.ts (21.57s)
PASS  src/__tests__/pulse-items/pulse-items-ws-res.handler.spec.ts (31.41s)
PASS …
```

perf(compiler): use moduleResolutionCache for Language Service's resolveModuleNames

---

e2e/__cases__/ts-jest-checks/index.spec.ts
src/__mocks__/tsconfig-project-references.json
src/__mocks__/tsconfig-src.json
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts

At the moment, only `compilerOptions` in `tsconfig.json` is considered in cache key. However, if users change other options like `include` or `exclude`, the cache isn't invalidated. Since `include/exclude` impacts on performance with `ts-jest`, it makes sense to include them into cache key.
This PR is to invalidate cache whenever other options (`include/exclude/projectReferences`) from `tsconfig.json` change 
Green CI
**N.A.**

fix(config): invalidate cache when other options in tsconfig change

---

docs/user/config/index.md
e2e/__tests__/__snapshots__/logger.test.ts.snap
e2e/__tests__/logger.test.ts
src/util/__snapshots__/backports.spec.ts.snap
src/util/backports.spec.ts
src/util/version-checkers.spec.ts
src/util/version-checkers.ts

- Allow opt-out version checking warning message via environment variable `TS_JEST_DISABLE_VER_CHECKER`
- Adjust documentation
Close #1774 
Added unit test and e2e test. Green CI
**N.A.**

feat: allow opt-out version checking by environment variable

---

package.json
src/__mocks__/thing.spec.ts
src/compiler/__snapshots__/language-service.spec.ts.snap
src/compiler/language-service.spec.ts
src/compiler/language-service.ts

Addressed in https://github.com/kulshekhar/ts-jest/issues/1506#issuecomment-663560350
The problem is that the test file can be renamed which then makes the link between the imported module with the old test name no longer valid. Therefore we need to check whether the test file still exists before doing type check.
Added unit test
Will release alpha first and then hot fix release later

fix(compiler): check if test file exists before doing type check

---

docs/user/config/astTransformers.md
e2e/__tests__/__snapshots__/logger.test.ts.snap
e2e/__tests__/logger.test.ts
src/__helpers__/fakers.ts
src/__mocks__/dummy-transformer.js
src/compiler/instance.ts
src/compiler/language-service.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/index.ts
src/types.ts
src/util/backports.ts
src/util/importer.ts
src/util/messages.ts

At the moment, we only support `before` AST transformers. There are 2 other types, `after` and `afterDeclarations` which we should support too. This PR does:
- Deprecate current way of defining `astTransformers` in `ts-jest` config by showing a warning message and instruct users how to migrate to the new way of config.
- Replace the current way of defining `astTransformers` with a new way, which is an object to be able to accept all 3 types of AST transformers.
- The old way of configuring will be removed in **v27**
Added unit tests and e2e tests, Green CI
**N.A.**

feat(config): support after and afterDeclarations AST transformers

---

src/config/config-set.spec.ts
src/config/config-set.ts

`projectPackageJson`, `projectDependencies`, `createTsError` getters are only used within `config-set.ts`, so it makes sense to set them as private getter
Adjusted unit test, Green CI
**N.A.**

refactor(config): set private for projectPackageJson, projectDependencies, createTsError getters

---

src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts

Set `get jest()` to private since it is not used outside `config-set.ts`.
Adjusted unit tests, green CI
**N.A.**

refactor(config): set jest getter to private getter

---

package-lock.json
package.json

Because we export `mocked`, a util function, as a public function but we also refer to `@types/jest` [here](https://github.com/kulshekhar/ts-jest/blob/1a44b700c7547de980196b6075c7610e9a86aeac/src/util/testing.ts#L7) which isn’t complied with yarn 2
This PR moves `@types/jest` to dependencies list.
Fixes #1857
Pack a tgz file and install with yarn 2 to the project in #1857
**N.A.**

fix: move @types/jest to dependencies to work well with yarn 2

---

src/config/config-set.spec.ts
src/config/config-set.ts

Mark `babelConfig` and `filterDiagnostics` as private getters because they are not used outside `config-set.ts`
Adjusted unit tests, green CI
**N.A.**

refactor(config): mark babelConfig and filterDiagnostics getters as private getters

---

package-lock.json
package.json

`jest-util` only exports `globsToMatcher` function since **26.1.0**. This PR sets the minimum version of `jest-util` to make sure that users get the correct version of `jest-util` to work with `ts-jest`.
Closes #1913
Green CI
**N.A.**

fix: set minimum jest-util version at 26.1.0

---

e2e/__cases__/hoisting/__test_modules__/banana.ts
e2e/__cases__/hoisting/__test_modules__/mockFile.ts
e2e/__cases__/hoisting/general-hoisting.spec.ts
e2e/__cases__/hoisting/import-jest.spec.ts
e2e/__tests__/__snapshots__/hoisting.test.ts.snap
e2e/__tests__/hoisting.test.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/transformers/__snapshots__/hoist-jest.spec.ts.snap
src/transformers/hoist-jest.spec.ts
src/transformers/hoist-jest.ts

Support hoisting when using `@jest/globals`, applying to:
- named import, e.g. `import { jest } from '@jest/globals'`
- aliased named import, e.g. `import {jest as aliasedJest} from '@jest/globals'`
- namespace import, e.g `import * as JestGlobals from '@jest/globals'`
Closes #1593 
Green CI
**N.A.**

feat(transformer): support hoisting when using `@jest/globals`

---

src/compiler/transpiler.ts

I found that Typescript's `createProgram` API is called even when `isolatedModule` is set. 
This is a major slow down (100 msecs vs 10~50 secs) for test start up and it doesn't seem to make sense for `isolatedModule` anyway. 
Longer test start up -> longer feedback cycle -> lower productivity. 
N/A. The `program` isn't used by any part of ts-jest, at least not in its critical path.
I just don't know enough about the use case of `program` for `isolatedModule`.
I tried to gather the history around this but couldn't find any notes regarding `transpiler`'s need for `program`. 
If the `createProgram` turned out to be desirable thing here, I am happy to create another PR to introduce a flag to disable it.
Otherwise, I believe majority of `isolatedModule` users will benefit from this PR greatly.

perf(transformer): remove createProgram from transpiler 

---

e2e/__cases__/hoisting/import-jest.spec.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/transformers/__snapshots__/hoist-jest.spec.ts.snap
src/transformers/hoist-jest.spec.ts
src/transformers/hoist-jest.ts

In #1937, we added support for `@jest/globals`. However, the logic to detect jest import name bindings wasn't correct. It failed with the case `import {test,jest} from '@jest/globals'`. This PR will fix that issue.
Adjusted unit test, e2e test. Green CI
**N.A.**

refactor(transformer): correctly detect jest import name bindings

---

docs/user/config/astTransformers.md
e2e/__cases__/ast-transformers/with-extra-options/foo.js
e2e/__cases__/ast-transformers/with-extra-options/with-extra-options.spec.ts
e2e/__tests__/__snapshots__/ast-transformers.test.ts.snap
e2e/__tests__/ast-transformers.test.ts
e2e/__tests__/path-mapping.test.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/types.ts

Continue #1946
Closes #1942
Green CI
**N.A.**

feat(config): allow custom options in custom transformers

---

e2e/__cases__/utils/src/foo/bar.ts
e2e/__cases__/utils/ts-jest-utils.spec.ts
e2e/__cases__/utils/tsconfig.json
src/config/__snapshots__/paths-to-module-name-mapper.spec.ts.snap
src/config/paths-to-module-name-mapper.spec.ts
src/config/paths-to-module-name-mapper.ts

Closes #1968
adjusted unit tests and e2e tests, green CI
**N.A.**

fix(utils): `pathsToModuleNameMapper` resolve path mapping with `path.join`

---

src/utils/testing.ts

At this point, `MaybeMockedConstructor` can return an empty object, causing the source type to be lost. This PR fixes this.
For example, the `mocked(MyClass.prototype)` function actually returns a new type that has the same properties as `MyClass.prototype`, but does not link to `MyClass.prototype`.
Because of this, you cannot click on a specific property and go to the source class. For the same reason, during refactoring, renaming properties in the source class does not rename the corresponding properties in the tests.

fix(utils): MaybeMockedConstructor returns T

---

e2e/__cases__/deep/src/Tests/jest.config.js
e2e/__external-repos__/simple-project-references/jest.config.js
e2e/__external-repos__/simple/with-dependency/package.json
e2e/__templates__/default/jest.config.js
e2e/__templates__/with-babel-7-string-config/jest.config.js
e2e/__templates__/with-babel-7/jest.config.js
e2e/__templates__/with-unsupported-version/jest.config.js
e2e/__tests__/ast-transformers.test.ts
e2e/__tests__/logger.test.ts
e2e/__tests__/module-kinds/helpers.ts
e2e/__tests__/source-map.test.ts
e2e/__tests__/test-helpers.test.ts
jest-base.js
src/compiler/language-service.spec.ts
src/compiler/transpiler.spec.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/transformers/path-mapping.spec.ts
src/utils/messages.ts

To avoid confusion, we should use `tsconfig` instead of `tsConfig`. This PR sets a warning log to instruct users to use `tsconfig`, as well as changing internal codes to use `tsconfig`.
The option `tsConfig` will be removed in **v27**
Added unit test, green CI
**N.A.**

refactor(config): deprecate option `tsConfig` in favor of `tsconfig`

---

src/config/config-set.spec.ts
src/config/config-set.ts
src/index.ts

`version` and `digest` is used by `ConfigSet` only. It makes sense to move these 2 to `ConfigSet`
Green CI
**N.A.**

refactor(config): move `version` and `digest` to `ConfigSet`

---

src/__helpers__/fakers.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/types.ts
src/utils/messages.ts

This option is not used internally so we can deprecate it and remove it in v27
Green CI
**N.A.**

refactor(config): deprecate `packageJson` option

---

src/compiler/instance.ts
src/config/config-set.ts
src/ts-jest-transformer.ts
src/utils/json.ts
src/utils/jsonable-value.ts

- Expose several properties in `ConfigSet`
- Expose `JsonableValue` and some json utils
- Expose `updateOutput` function in compiler
TypeScript doesn't allow subclass to use parent class getters so we have to convert public getters to public properties, see https://github.com/microsoft/TypeScript/issues/338
Green CI
**N.A.**

feat(config): expose several typings as public apis

---

src/config/config-set.spec.ts
src/config/config-set.ts

Closes #2064
Added unit test, green CI
**N.A.**

fix(config): resolve `.babelrc` file before attempting to read it

---

src/compiler/language-service.ts
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/constants.ts
src/ts-jest-transformer.ts

- Allow to override `readTsConfig`
- Expose `_transformCfgStr`, `_configSet`, `_overriddenCompilerOptions`
Green CI
**N.A.**

feat(config): allow to override `readTsConfig`

---

src/utils/testing.ts

Expose typings for util `mocked`
Closes #2086
Green CI
**N.A.**

feat(testing): expose all types for util `mocked`

---

docs/user/install.md

New versions of Jest ship with type definitions. Indeed, Jest is being re-written in TypeScript. 
n/a
n/a
n/a

Removes redundant type definition install instruction

---

e2e/__tests__/__snapshots__/coverage.test.ts.snap
e2e/__tests__/coverage.test.ts
package.json
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Revert #2020
Closes #2080
Closes #2090
Closes #2104
Green CI
**N.A.**

fix: revert usage of `@jest/create-cache-key-function`

---

docs/user/config/index.md
docs/user/config/tsconfig.md
e2e/__tests__/__snapshots__/logger.test.ts.snap
e2e/__tests__/logger.test.ts
src/__helpers__/fakers.ts
src/cli/cli.spec.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/transformers/path-mapping.spec.ts
src/types.ts
src/utils/__snapshots__/backports.spec.ts.snap
src/utils/backports.ts
src/utils/messages.ts

Remove support for `tsConfig`.
Adjusted tests and docs
Green CI
One currently use `tsConfig` should change to `tsconfig` in your `jest.config.js` or `package.json`
**N.A.**

refactor(config): remove support for `tsConfig` option

---

src/config/config-set.spec.ts
src/config/config-set.ts

Default fall back to `ES2015` target when performing code compilation if no `target` is defined in `tsconfig`
Added unit test, green CI
**N.A.**

refactor(config): fall back to `ES2015` when no `target` is defined

---

e2e/__external-repos__/custom-typings/package.json
e2e/__external-repos__/custom-typings/yarn.lock
e2e/__external-repos__/memory-usage/package.json
e2e/__external-repos__/memory-usage/yarn.lock
e2e/__external-repos__/path-mapping/package.json
e2e/__external-repos__/path-mapping/yarn.lock
e2e/__external-repos__/simple-project-references/package.json
e2e/__external-repos__/simple-project-references/yarn.lock
e2e/__external-repos__/simple/with-dependency/package.json
e2e/__external-repos__/simple/with-dependency/yarn.lock
e2e/__external-repos__/yarn-workspace-composite/package.json
e2e/__external-repos__/yarn-workspace-composite/yarn.lock
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7-string-config/package-lock.json
e2e/__templates__/with-babel-7-string-config/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
src/index.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

- Allow any subclasses which extend `TsJestTransformer` to have version checking
- Update e2e deps
Added unit test, Green CI
**N.A.**

feat: allow subclass of `TsJestTransformer` to have version checking

---

src/__helpers__/fakers.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Convert several getters to public methods/public properties for `ConfigSet` because IDE complains  about
```
Accessors are only available when targeting ECMAScript 5 and higher.
```
Since we are building with target `es5`, therefore complaining is there
Green CI
**N.A.**

refactor(config): convert getters to methods/properties in `ConfigSet`

---

e2e/__helpers__/test-case/runtime.ts
e2e/__helpers__/test-case/types.ts
e2e/__helpers__/test-case/utils.ts
e2e/__tests__/allow-js.test.ts
e2e/__tests__/module-kinds/__snapshots__/amd.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/commonjs.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/es2015-esm.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/es2015.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/esnext-esm.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/esnext.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/none.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/system.test.ts.snap
e2e/__tests__/module-kinds/__snapshots__/umd.test.ts.snap
e2e/__tests__/module-kinds/amd.test.ts
e2e/__tests__/module-kinds/commonjs.test.ts
e2e/__tests__/module-kinds/es2015-esm.test.ts
e2e/__tests__/module-kinds/es2015.test.ts
e2e/__tests__/module-kinds/esnext-esm.test.ts
e2e/__tests__/module-kinds/esnext.test.ts
e2e/__tests__/module-kinds/helpers.ts
e2e/__tests__/module-kinds/none.test.ts
e2e/__tests__/module-kinds/system.test.ts
e2e/__tests__/module-kinds/umd.test.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

When `extensionsToTreatAsEsm` option is not an empty array, `CommonJS` enforcement will be no longer applicable.
Closes #1709 
Closes #2057 
Adjusted unit tests and e2e tests, green CI
To run tests with ESM support, one needs to make sure that:
- `module` in tsconfig should be either `es2015` or `es2020` or `esnext` 
- Use `ts-jest` ESM presets or define value for `extensionsToTreatAsEsm` option properly
**N.A**

feat: unforce module `CommonJS` when testing with ESM 

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-jest-compiler.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/ts-jest-transformer.ts
src/types.ts

- Make supportsStaticESM a mandatory arg for `getCompiledOutput`
- `_resolveTsConfig` only does finding and getting tsconfig. Override options will be done by a private method `_getAndResolveTsConfig`
- Rename `TsJestProjectConfig` to `ProjectConfigTsJest`

refactor(config): `_resolveTsConfig` only finds and gets tsconfig

---

src/__helpers__/path.ts
src/__helpers__/processed-source.ts
src/compiler/__snapshots__/ts-compiler.spec.ts.snap
src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts
src/transformers/hoist-jest.spec.ts
website/docs/esm-support.md
website/docs/options/useESM.md

Add support transforming codes to ESM syntax for `isolatedModules: false`
Added unit tests
**N.A.**

feat(compiler): support ESM for `isolatedModules: false`

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts
tsconfig.spec.json

Create a copy of initial compiler options and reuse them later for processing.
Adjusted unit tests, green CI
**N.A.**

refactor(compiler): prevent side effects for compiler options

---

src/config/config-set.spec.ts
src/config/config-set.ts
src/constants.ts

When `allowJs` is `true`, `ts-jest` will process `js` files and also perform type checking. However, since default behavior of TypeScript is not doing type checking on `js` files (`checkJs` default value is `false`), we should respect that behavior.
Added unit test, green CI
If one currently relies on type check for `js` files, please set `checkJs: true` in your tsconfig
**N.A.**

feat(config): type checking `js` files based on `checkJs`

---

src/compiler/__snapshots__/ts-compiler.spec.ts.snap
src/compiler/ts-compiler.spec.ts
src/config/config-set.spec.ts
src/config/config-set.ts
src/types.ts
src/utils/__snapshots__/backports.spec.ts.snap
src/utils/backports.ts
website/docs/options/diagnostics.md

- Replace `pathRegex` by `exclude` which uses Glob patterns, similar to tsconfig `exclude` option. This will make it easier to configure files to exclude from type checking.
- Adjust documentation
Partially related to #2258 
Adjusted unit tests, green CI
One is currently using `pathRegex` should use `exclude` with Glob patterns
**N.A.**

feat(config): replace `pathRegex` with `exclude`

---

e2e/__cases__/typings/jest-config-typings.spec.ts
e2e/__tests__/ts-jest-typings.test.ts
src/types.ts
website/docs/getting-started/installation.md
website/docs/getting-started/options.md
website/src/pages/index.js
website/versioned_docs/version-26.5/getting-started/options.md
website/versioned_docs/version-26.5/guides/esm-support.md

Related to #2325
Added e2e tests, green CI
**N.A.**

feat(config): support typed config options for jest config typescript

---

.eslintignore
e2e/__tests__/module-kinds/helpers.ts
presets/index.d.ts
src/cli/helpers/presets.ts
src/presets/create-jest-preset.ts
src/types.ts
website/docs/getting-started/presets.md

Add `index.d.ts` for `presets` folder
Closes #2325 
Added e2e test, green CI
**N.A.**

feat(presets): add typing for `presets` entry point

---

src/compiler/ts-compiler.ts

Expose `TsCompiler` as public api
Green CI
**N.A.**

feat(compiler): expose `TsCompiler` as public api

---

src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.ts
src/transformers/README.md
src/transformers/hoist-jest.spec.ts
src/transformers/hoist-jest.ts
src/transformers/path-mapping.spec.ts
src/transformers/path-mapping.ts
src/ts-jest-transformer.ts

Add `astTransformers` value to cache key
Green CI
**N.A.**

fix(config): invalidate Jest transform cache when `astTransformers` value changes

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Cache `depGraphs` and `tsResolvedModulesCachePath` to have type check properly in watch mode 
Added unit test
**N.A.**

fix(config): cache `depGraphs` and `tsResolvedModulesCachePath` to have type check properly in watch mode

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Expose `_createConfigSet` and `_createCompiler` methods so subclasses can just use those if they need to create their own instances. 
Added unit tests, green CI
**N.A.**

refactor(config): expose only create config set and compiler apis

---

src/__mocks__/dummy-transformer.js
src/config/config-set.ts

Related https://github.com/kulshekhar/ts-jest/issues/2371
This error occurs when accessing a `tsCompiler` object from a `factory` method inside `custom transformers`.
`npm test` passed

fix(config): define matchTestFilePath before setupTsJestCfg

---

src/compiler/ts-compiler.ts
src/config/config-set.spec.ts
src/config/config-set.ts

Revert partially #2358 
Closes #2350
Closes #2374
Green CI
**N.A.**

fix(compiler): exclude files in `outDir` from compiler source files

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts
src/compiler/ts-jest-compiler.ts
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts
src/types.ts

Separate compiler file content cache and jest file content cache. When compiling and type checking, comparing a file content from compiler file content cache against jest file content cache so that `LanguageService` is updated correctly.
Closes #2118 
Added unit test, Green CI
**N.A.**

fix(compiler): compile and type check correctly in watch mode when file content itself changes

---

src/compiler/ts-compiler.ts
src/utils/messages.ts

Closes #2407
Green CIC
**N.A.**

fix(compiler): return original file content and show warning on emit skip

---

package-lock.json
package.json
website/docs/getting-started/installation.md
website/versioned_docs/version-26.5/getting-started/installation.md

This will make Yarn 2 complain but there is no other way to do it.
Closes #2406
Closes #2411 
Green CI
**N.A.**

fix: remove `@types/jest` from direct dep

---

src/compiler/language-service.ts

Limit the initial list of file names for `LanguageService` to only include `.ts`/`.tsx`/`.d.ts` files
Closes #2445
Green CI
**N.A.**

fix(compiler): initialize compiler with `.ts`/`.tsx`/`.d.ts` files only

---

e2e/__cases__/presets/ts-jest-presets.spec.ts
package.json

Declare missing export for `jest-preset` which made `const defaultPreset = require('ts-jest/jest-preset')` failed
Adjusted e2e test, green CI
**N.A.**

fix: declare missing export for `jest-preset`

---

website/docs/getting-started/presets.md
website/versioned_docs/version-26.5/getting-started/presets.md

If I'm this is a typo, I had to make the change locally for node to resolve the presets correctly.
Eitherway there is some incoherence in the doc or their.
> https://kulshekhar.github.io/ts-jest/docs/next/getting-started/presets
```js
// jest.config.js
const { defaults: tsjPreset } = require('ts-jest/presets')
// const { defaultsESM: tsjPreset } = require('ts-jest/presets')
// const { jsWithTs: tsjPreset } = require('ts-jest/presets')
// const { jsWithTsESM: tsjPreset } = require('ts-jest/presets')
// const { jsWithBabel: tsjPreset } = require('ts-jest/presets')
// const { jsWithBabelESM: tsjPreset } = require('ts-jest/presets')
module.exports = {
// [...]
transform: {
...tsjPreset.transform,
// [...]
},
}
```
```
// jest.config.ts
import type { InitialOptionsTsJest } from …
```

typo(package.json): preset -> presets

---

e2e/__external-repos__/custom-typings/package.json
e2e/__external-repos__/custom-typings/yarn.lock
e2e/__external-repos__/memory-usage/package.json
e2e/__external-repos__/memory-usage/yarn.lock
e2e/__external-repos__/path-mapping/package.json
e2e/__external-repos__/path-mapping/yarn.lock
e2e/__external-repos__/simple-project-references/package.json
e2e/__external-repos__/simple-project-references/yarn.lock
e2e/__external-repos__/simple/with-dependency/package.json
e2e/__external-repos__/simple/with-dependency/yarn.lock
e2e/__external-repos__/yarn-workspace-composite/package.json
e2e/__external-repos__/yarn-workspace-composite/yarn.lock
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7-string-config/package-lock.json
e2e/__templates__/with-babel-7-string-config/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
package-lock.json
package.json
src/utils/version-checkers.spec.ts
src/utils/version-checkers.ts

Support **27.0.0-next.7**
Green CI
**N.A.**

feat: support jest **27.0.0-next.7**

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts
src/utils/messages.ts

When encountering `emitSkipped`:
- Return file content and show a warning message for non `ts`/`tsx` files.
- Throw error for `ts`/`tsx` files
Closes #2513 
Added unit test
Green CI
**N.A.**

fix(compiler): return file content on emitSkipped for non ts/tsx files

---

e2e/__external-repos__/custom-typings/package.json
e2e/__external-repos__/custom-typings/yarn.lock
e2e/__external-repos__/memory-usage/package.json
e2e/__external-repos__/memory-usage/yarn.lock
e2e/__external-repos__/path-mapping/package.json
e2e/__external-repos__/path-mapping/yarn.lock
e2e/__external-repos__/simple-project-references/package.json
e2e/__external-repos__/simple-project-references/yarn.lock
e2e/__external-repos__/simple/with-dependency/package.json
e2e/__external-repos__/simple/with-dependency/yarn.lock
e2e/__external-repos__/yarn-workspace-composite/package.json
e2e/__external-repos__/yarn-workspace-composite/yarn.lock
e2e/__templates__/default/package-lock.json
e2e/__templates__/default/package.json
e2e/__templates__/with-babel-7-string-config/package-lock.json
e2e/__templates__/with-babel-7-string-config/package.json
e2e/__templates__/with-babel-7/package-lock.json
e2e/__templates__/with-babel-7/package.json
e2e/__templates__/with-unsupported-version/package-lock.json
e2e/__templates__/with-unsupported-version/package.json
src/compiler/compiler-utils.ts
src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts
src/config/config-set.ts
tsconfig.json

This is the functionality we had in the past before **23.10** but was lost after **23.10**. This PR is to bring it back.
The original request was #469
Green CI
By default, `ts-jest` will use `sourceMap` option from test `tsconfig`. If users want to have sourcemap on, they need to either remove `sourceMap` from `tsconfig` or set `sourceMap: true` 
**N.A.**

feat(config): allow disable sourcemap

---

src/config/config-set.spec.ts
src/config/config-set.ts
src/utils/messages.ts

Show a warning message when users are using `sourceMap: false` in test. This will provide a migration step which is related to #2544 
Green CI
**N.A.**

refactor(config): show warning message for `sourceMap: false`

---

CHANGELOG.md
src/cli/__snapshots__/cli.spec.ts.snap
src/cli/cli.spec.ts
src/cli/config/migrate.ts

The issue happens when `testRegex` is an empty array. This PR adds a few changes:
- Instead of set `testMatch` to `null`, delete `testMatch` from migrated config.
- Only delete `testMatch` from migrated config when `testRegex` is a string or a non-empty array.
- Improved codes to use optional chaining and nullish coalescing.
Closes #2616
Added unit tests
Green CI
**N.A.**

fix(cli): keep `testMatch` if old jest config contains it

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts

When a file initially exists in compiler file set when `TsCompiler` is created, later in `getCompiledOutput` the value of `compilerOptions` which makes `LanguageService` is not aware of because `_updateMemoryCache` checks and sees that the file is the same so `projectVersion` value is not increased which makes `LanguageService` uses the outdated `_compilerOptions`.
This commit adds a comparison via JSON stringify between `_compilerOptions` and `_initialCompilerOptions`. If there is a difference, increase `projectVersion` for `LanguageService`.
This regression came to light when bumping vue-jest to ts-jest v27.
The tsconfig used has : `"module": "es2015"`, and `ts-jest` used to compile the files to commonjs anyway.
This is no longer the case when using ts-jest v27.0.0
Closes #2629 
Added …

fix(compiler): make sure language service use updated compiler options

---

e2e/__external-repos__/simple/with-dependency/package.json
e2e/__external-repos__/simple/with-dependency/tsconfig.json
package-lock.json
package.json
scripts/lib/paths.js
src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts

File content empty string should be added to compiler file cache otherwise compiler will fail to compile other files.
Closes #2625 
Updated e2e test and unit test
Green CI
**N.A.**

fix(compiler): add file content empty string to compiler cache

---

src/config/config-set.spec.ts
src/config/config-set.ts

Reverse logic to check whether a file should be type checked to suit the usage of `exclude`.
Closes #2634
Green CI
**N.A.**

fix(config): `exclude` should only exclude files which match glob values

---

src/compiler/ts-compiler.spec.ts
src/compiler/ts-compiler.ts

Compare `module` value is faster than comparing stringified compiler options.
Related to #2628 
Adjusted unit test
Green CI
**N.A.**

refactor(compiler): increase project version based on `module` value

---

package.json

Subpath exports don't work with Node 10 and Node < 12.20.0 so we have to revert the `exports` declaration in `package.json` so that consumers of `ts-jest` can still use `ts-jest` public apis.
Related issue https://github.com/thymikee/jest-preset-angular/issues/941
See https://github.com/ahnpnl/jest-preset-angular/actions/runs/902838031
**N.A.**

fix: revert `exports` field to support all node versions

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

This allows to detect on runtime that the code is executed via jest with TS support enabled via ts-jest. Works via setting environment variable `TS_JEST=1`.
Closes #2716
I am author of MikroORM. It allows to discover entities either via references (entities: [User]) or via paths (entities: ['./entities']). To use the folder based discovery, I need to operate on the TS files when running via ts-node or ts-jest, as I am attaching some properties to the entity prototype and therefore need to work with TS file if that is what will be later used on runtime (in other words, if ts-node/ts-jest is used, I need to discover TS files from src, otherwise JS files from dist).
To deal with this, I have two different config options for entity paths, one for JS files, one for TS files. If I am able to …

feat: set env var `TS_JEST` to allow detecting of ts-jest

---

src/__mocks__/hummy-transformer.js
src/config/__snapshots__/config-set.spec.ts.snap
src/config/config-set.spec.ts
src/config/config-set.ts
src/transformers/README.md
src/transformers/hoist-jest.ts
src/transformers/path-mapping.ts
src/utils/messages.ts

- Include transformer name and version into cache key
- Remove typescript object from cache key because this is a huge object and stringify + hash it will take time.
Closes #2753 
Updated unit tests
Green CI
**N.A.**

fix(config): include AST transformer's name and version into cache key

---

package.json

The `mocked` function [helper](https://kulshekhar.github.io/ts-jest/docs/guides/test-helpers) requires a project to have `@types/jest` installed. However, we can't force users to install a type package so the way to go is declare it in the list of optional `peerDependencies`
Create a `tgz` file of `ts-jest` and install on any projects, there shouldn't have any warnings about missing peer dependency for `@types/jest`
**N.A**

fix: add `@types/jest` as optional `peerDependencies` to solve yarn 2 problem

---

src/cli/cli.spec.ts
src/cli/config/init.ts

This fixes `ts-jest config:init` generated file's type error.
When I ran `npx ts-jest config:init` then I have a following error in generated `jest.config.js`.
> Cannot find module '@ts-jest/dist/types' or its corresponding type declarations.
Because ts-jest is installed in node_modules/ts-jest not node_modules/@ts-jest.
Run `npx ts-jest config:init` then you don't have any errors in generated `jest.config.js` .
Fixes #2772

fix: fix config:init types

---

website/docs/getting-started/options.md
website/versioned_docs/version-27.0/getting-started/options.md

Closes #2795 
Green CI
**N.A.**

docs(devs-infra): add note when using TypeScript Jest config file

---

src/config/__snapshots__/paths-to-module-name-mapper.spec.ts.snap
src/config/paths-to-module-name-mapper.spec.ts
src/config/paths-to-module-name-mapper.ts

Closes #2709
Updated unit tests
Green CI
**N.A.**

fix(config): fix `pathsToModuleNameMapper` with `./` in tsconfig `paths`

---

TROUBLESHOOTING.md

When setting up a project with @vue/cli (https://github.com/vuejs/vue-cli) with version 4.5.13 with ts-jest I faced the problem that the test could not be executed for my component because one of the modules doesn't need to be transpiled.
I found this answer after searching for a long time on the web and therefore thought it should be added to the documentation of the project. 
There are no changes in the code. In can be tested as follows:
1. Setup a vue project with vue-cli: `vue create project`
2. Select Vue2.x, typescript, jest and babel
3. Add the vue-class-component package via `npm install --save vue vue-class-component`
4. Adapt the `HelloWorld.vue` component:
5. 
```
<script lang="ts">
import Vue from "vue";
import Component from "../../node_modules/vue-class-component/lib"; …
```

Docs: Troubleshoot import statement

---

package-lock.json
package.json

This library is built to work with Jest 27. However, it uses the types for Jest 26, as types for Jest 27 were not available until recently. This PR updates the peer dependencies for version 27.
Everything still builds happily
However, users with old versions of `@types/jest` will see a warning (which has no effect apart from displaying this warning) that they're using a different optional peer dependency version.
All I did was change the version of `@types/jest` to 27 and then did an `npm install` - not sure why it wanted to move around the ordering in the package.json :shrug:

build(deps): bump @types/jest to v27

---

website/docs/guides/esm-support.md
website/versioned_docs/version-27.0/guides/esm-support.md

this PR adds the necessary code to the ESM docs config examples to enable `"type": "module"` typescript packages to use `ts-jest` for testing. reference: https://github.com/kulshekhar/ts-jest/issues/1709#issuecomment-869567343
it’s a docs change, no test plan i can think of

Update example ESM configs to support ESM-compatible imports that include .js extension

---

e2e/__tests__/enum.test.ts
e2e/__tests__/extend-ts-jest.test.ts
e2e/extend-ts-jest/__tests__/foo.spec.ts
e2e/extend-ts-jest/foo-transformer.js
e2e/extend-ts-jest/package.json
src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Allow subclasses to extend `processAsync` and `getCacheKeyAsync` methods
Added e2e test, unit test can't test this
Green CI
**N.A.**

feat: allow extending `processAsync` and `getCacheKeyAsync`

---

e2e/__tests__/custom-compiler.test.ts
e2e/custom-compiler/ttypescript/__tests__/direct-import.spec.ts
e2e/custom-compiler/ttypescript/package-lock.json
e2e/custom-compiler/ttypescript/package.json
e2e/custom-compiler/ttypescript/share/foo.ts
e2e/custom-compiler/ttypescript/tsconfig.json
src/types.ts

Added missing e2e tests for `ttypescript` support
**N.A.**

refactor: define clear type for `compiler` option in `ts-jest` config

---

.github/workflows/ci.yml
src/utils/testing.ts

Add a warning about deprecation of `mocked` util function
Green CI
**N.A.**

refactor(utils): deprecate `mocked` util function

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Addressed by https://github.com/kulshekhar/ts-jest/discussions/3131#discussioncomment-1760522
Added unit test
Green CI
**N.A.**

fix: bring back `afterProcess` hook

---

src/types.ts

Addressed in https://github.com/kulshekhar/ts-jest/pull/3129#issuecomment-990758729
Green CI
**N.A.**

fix: stimulate `esbuild` type to avoid importing `esbuild` directly

---

src/compiler/ts-compiler.ts

The ts-jest transform is currently ignoring the file content it receives until there is already a hit in the memory cache. That prevents us from doing things like chaining transforms (see https://github.com/anc95/jest-chain-transform), as ts-jest will just read the original file from disk and ignore the transformation. It should also be affecting people trying to do this: https://github.com/kulshekhar/ts-jest/discussions/2721
I'm saying no, as this feature was previously non-functional so no one should be relying on the current behavior, but I guess it could be yes if we're very strict and want to support someone misusing the transform.
The changes I'm proposing were enough to resolve the issue for my use case. I haven't done extensive research into it, but it seems pretty straightforward …

Fix: transform using received file content

---

website/versioned_docs/version-27.1/getting-started/paths-mapping.md

Docs update only. Updates the `ts-jest` import to `ts-jest/utils` as per the following warning produced by `ts-jest`:
> ts-jest[root] (WARN) The `pathsToModuleNameMapper` helper has been moved to `ts-jest/utils`. Use `import { pathsToModuleNameMapper } from 'ts-jest/utils'` instead.
n/a
n/a

Update ts-jest import

---

package.json

Closes #3346 
- Pack `ts-jest` with `npm pack`
- Install the `tgz` file together with `esbuild@0.12.28` to a project using Yarn 2+
- Check if the warning no longer appears like reported in #3346 
**N.A.**

fix: remove `esbuild` from peer dependency

---

.github/workflows/ci.yml
.github/workflows/doc-generator.yml
.github/workflows/release-and-publish.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

Set permissions for GitHub actions

---

src/ts-jest-transformer.spec.ts
src/ts-jest-transformer.ts

Previously we always invoke `process` for ESM mode. However, in `process` we also invoke Babel `process`, which is wrong because `babel-jest` has `processAsync` which is for ESM mode. This was discovered while doing #3429
Green CI
**N.A.**

fix: invoke `processAsync` of `babel-jest` in ESM mode instead of `process`

---

e2e/__tests__/__snapshots__/const-enum.test.ts.snap
e2e/__tests__/__snapshots__/enum.test.ts.snap
e2e/transform-tsx/package-lock.json
e2e/transform-tsx/package.json
examples/js-with-babel/package-lock.json
examples/js-with-babel/package.json
examples/js-with-ts/package-lock.json
examples/js-with-ts/package.json
examples/react-app/package-lock.json
examples/react-app/package.json
examples/ts-only/package-lock.json
examples/ts-only/package.json
package-lock.json
package.json
scripts/test-examples.js
src/utils/version-checkers.spec.ts
src/utils/version-checkers.ts

feat: set Jest peer dependencies to v28

---

e2e/presets/__tests__/presets.spec.ts
presets/default-esm-legacy/jest-preset.js
presets/default-legacy/jest-preset.js
presets/index.d.ts
presets/index.js
presets/js-with-babel-esm-legacy/jest-preset.js
presets/js-with-babel-legacy/jest-preset.js
presets/js-with-ts-esm-legacy/jest-preset.js
presets/js-with-ts-legacy/jest-preset.js
src/index.ts
src/legacy/index.ts
src/presets/__snapshots__/create-jest-preset.spec.ts.snap
src/presets/create-jest-preset.spec.ts
src/presets/create-jest-preset.ts
website/docs/getting-started/presets.md
website/docs/guides/esm-support.md

Add several presets for legacy mode and update documentation
Updated tests
Green CI
**N.A.**

feat(presets): add presets for legacy mode

---

website/docs/getting-started/options/diagnostics.md
website/versioned_docs/version-26.5/getting-started/options/diagnostics.md
website/versioned_docs/version-27.0/getting-started/options/diagnostics.md
website/versioned_docs/version-27.1/getting-started/options/diagnostics.md

Fixes #3488 the wrong example at [Enabling diagnostics for test files only](https://kulshekhar.github.io/ts-jest/docs/getting-started/options/diagnostics#enabling-diagnostics-for-test-files-only) by adding negation `!`. Also adds `(spec|test)` part since the doc mentions both.
The changes have been made for all docs versions.

fix(docs): fix the example for enabling diagnostics for test files only

---

src/transformers/hoist-jest.ts

When hoist-jest encounters a file with a large enough number of statements to sort, it can error with `Maximum call stack size exceeded`
Use existing hoist-jest tests + tested change against our project.
Closes: #3476

Use Array.sort in hoist-jest

---

package.json
renovate.json

Since we already removed `mocked`, `@types/jest` is no longer required as peer dep
Green CI
**N.A.**

fix: remove `@types/jest` from peer deps

---

examples/ts-only/tsconfig.json
src/legacy/compiler/ts-compiler.spec.ts
src/legacy/compiler/ts-compiler.ts
src/legacy/compiler/ts-jest-compiler.ts
src/legacy/config/config-set.ts
src/legacy/ts-jest-transformer.ts
src/types.ts

Fixes #3507 
Green CI
**N.A.**

fix(legacy): throw type check error in ESM mode with `reject`

---

package.json

As `@jest/types` is imported in `src/types.ts` and it is present in documentation saying it is required to be installed. It should be listed in the package.json as peerDependencies

Set @jest/types as peer dependency

---

.npmignore

Add `renovate.json` to the `.npmignore` file with the goal of excluding it from releases of ts-jest to npm.
No code changes were made.
I was comparing [the diff between 28.0.3 and 28.0.5](https://app.renovatebot.com/package-diff?name=ts-jest&from=28.0.3&to=28.0.5) and noticed this file was added. As it's not needed I figured I can add it to the `.npmignore` file so it's not included in future releases.

Add `renovate.json` to `.npmignore`

---

e2e/diagnostics/__tests__/diagnostics.spec.ts
e2e/utils.ts
src/legacy/config/config-set.spec.ts
src/legacy/config/config-set.ts

Fixes #3638 
Green CI
**N.A.**

fix(config): don't show diagnostics warning with `diagnostics: false`

---

src/constants.ts
src/legacy/ts-jest-transformer.spec.ts
src/presets/__snapshots__/create-jest-preset.spec.ts.snap

Fixes #3702 
Green CI
**N.A.**

fix: allow `.mts` to be processed

---

e2e/__tests__/native-esm-ts.test.ts
e2e/native-esm-ts/__tests__/native-esm-ts.spec.ts
e2e/native-esm-ts/jest-isolated.config.js
e2e/native-esm-ts/mjs-resolver.ts
e2e/native-esm-ts/package-lock.json
e2e/native-esm-ts/package.json
e2e/native-esm-ts/triple.mts
e2e/native-esm-ts/tsconfig.json

test(e2e): add `mts` e2e test

---

e2e/__tests__/__snapshots__/const-enum.test.ts.snap
e2e/__tests__/__snapshots__/enum.test.ts.snap
e2e/native-esm-ts/package-lock.json
e2e/native-esm-ts/package.json
e2e/transform-tsx/package-lock.json
e2e/transform-tsx/package.json
package-lock.json
package.json
src/cli/__snapshots__/cli.spec.ts.snap
src/cli/cli.spec.ts
src/config/__snapshots__/paths-to-module-name-mapper.spec.ts.snap
src/config/paths-to-module-name-mapper.spec.ts
src/legacy/compiler/__snapshots__/ts-compiler.spec.ts.snap
src/legacy/config/__snapshots__/config-set.spec.ts.snap
src/legacy/config/config-set.spec.ts
src/legacy/ts-jest-transformer.spec.ts
src/presets/__snapshots__/create-jest-preset.spec.ts.snap
src/transformers/__snapshots__/hoist-jest.spec.ts.snap
src/utils/__snapshots__/backports.spec.ts.snap
src/utils/importer.spec.ts
src/utils/version-checkers.spec.ts
src/utils/version-checkers.ts

Adopt https://github.com/facebook/jest/releases/tag/v29.0.0
Green CI

build(devs-dep): adopt Jest 29.0.0

---

src/legacy/ts-jest-transformer.ts

When creating `ConfigSet` with migrated Jest config (to migrate from `globals` to transformer config), it is a must to also copy other globals config.
Green CI
**N.A.**

fix(legacy): include existing globals config in cached config

---

website/docs/debugging.md
website/docs/getting-started/installation.md
website/docs/getting-started/options.md
website/docs/getting-started/options/astTransformers.md
website/docs/getting-started/options/babelConfig.md
website/docs/getting-started/options/compiler.md
website/docs/getting-started/options/diagnostics.md
website/docs/getting-started/options/isolatedModules.md
website/docs/getting-started/options/stringifyContentPathRegex.md
website/docs/getting-started/options/tsconfig.md
website/docs/getting-started/options/useESM.md
website/docs/getting-started/paths-mapping.md
website/docs/getting-started/presets.md
website/docs/guides/esm-support.md
website/docs/guides/mock-es6-class.md
website/docs/guides/react-native.md
website/docs/migration.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Using `@docusaurus/remark-plugin-npm2yarn` and `docusaurus-remark-plugin-tab-blocks` which will do:
becomes 
Green CI
**N.A.**

docs(devs-infra): add tabs for js/ts and shell

---

website/docs/getting-started/options.md
website/docs/getting-started/options/astTransformers.md
website/docs/getting-started/options/babelConfig.md
website/docs/getting-started/options/compiler.md
website/docs/getting-started/options/diagnostics.md
website/docs/getting-started/options/stringifyContentPathRegex.md
website/docs/getting-started/options/tsconfig.md
website/docs/getting-started/options/useESM.md
website/docs/getting-started/paths-mapping.md
website/docs/getting-started/presets.md
website/docs/guides/esm-support.md
website/docs/guides/react-native.md
website/versioned_docs/version-29.0/getting-started/options.md
website/versioned_docs/version-29.0/getting-started/options/astTransformers.md
website/versioned_docs/version-29.0/getting-started/options/babelConfig.md
website/versioned_docs/version-29.0/getting-started/options/compiler.md
website/versioned_docs/version-29.0/getting-started/options/diagnostics.md
website/versioned_docs/version-29.0/getting-started/options/stringifyContentPathRegex.md
website/versioned_docs/version-29.0/getting-started/options/tsconfig.md
website/versioned_docs/version-29.0/getting-started/options/useESM.md
website/versioned_docs/version-29.0/getting-started/paths-mapping.md
website/versioned_docs/version-29.0/getting-started/presets.md
website/versioned_docs/version-29.0/guides/esm-support.md
website/versioned_docs/version-29.0/guides/react-native.md

`JestConfigWithTsJest` type imports do not look correct in current docs. At least they don’t work if copy-pasted.
Deploy preview.

docs: fix `JestConfigWithTsJest` type import in examples

---

tsconfig.build.json

Currently the library is build with `"removeComments": true` set and most probably there is a reason for that.
Just wanted to draw your attention that that together with other comments `@deprecated` tags are getting removed as well. The JSDoc comments are also missing in the build file. Aren’t these supposed to reach the users?
Checked output files in the `dist` directory locally.

build: do not remove comments

---

website/docs/getting-started/options/compiler.md
website/docs/getting-started/options/diagnostics.md
website/docs/getting-started/options/isolatedModules.md
website/docs/getting-started/options/tsconfig.md
website/docs/getting-started/options/useESM.md
website/docs/guides/esm-support.md
website/versioned_docs/version-29.0/getting-started/options/compiler.md
website/versioned_docs/version-29.0/getting-started/options/diagnostics.md
website/versioned_docs/version-29.0/getting-started/options/isolatedModules.md
website/versioned_docs/version-29.0/getting-started/options/tsconfig.md
website/versioned_docs/version-29.0/getting-started/options/useESM.md
website/versioned_docs/version-29.0/guides/esm-support.md

This PR add missing closing `>` in code examples in docs.

docs: add missing closing character

---

e2e/config-typing/jest.config.ts
src/types.ts

This PR attempts to solve the globals type issue mentioned [here](https://github.com/kulshekhar/ts-jest/issues/3815), that 'ts-jest' should be optional in globals.
I've run `test` and it was passed

fix: 'ts-jest' should be optional in ConfigGlobals

---

src/cli/cli.spec.ts
src/cli/config/init.ts
src/types.ts

Updated tests
Green CI
**N.A.**

fix: use transformer config in `config:init` instead of `globals`

---

e2e/presets/__tests__/presets.spec.ts
examples/js-with-babel/package-lock.json
examples/js-with-babel/package.json
examples/js-with-ts/package-lock.json
examples/js-with-ts/package.json
examples/react-app/package-lock.json
examples/react-app/package.json
examples/ts-only/package-lock.json
examples/ts-only/package.json
examples/type-module/globals.d.ts
examples/type-module/jest-esm-isolated.config.js
examples/type-module/jest-esm.config.js
examples/type-module/jest-isolated.config.js
examples/type-module/jest.config.js
examples/type-module/package-lock.json
examples/type-module/package.json
examples/type-module/src/welcome-message.spec.ts
examples/type-module/src/welcome-message.ts
examples/type-module/tsconfig-esm.json
examples/type-module/tsconfig.json
src/cli/__snapshots__/cli.spec.ts.snap
src/cli/config/init.ts
src/cli/config/migrate.ts
src/presets/__snapshots__/create-jest-preset.spec.ts.snap
src/presets/create-jest-preset.ts
src/types.ts

Addressed in https://github.com/kulshekhar/ts-jest/issues/3828#issuecomment-1256572241 and https://github.com/kulshekhar/ts-jest/issues/3800#issuecomment-1247761011
Green CI
**N.A.**

fix(presets): allow merging transform config when using presets

---

website/docs/getting-started/options.md
website/docs/getting-started/options/astTransformers.md
website/docs/getting-started/options/babelConfig.md
website/docs/getting-started/options/compiler.md
website/docs/getting-started/options/diagnostics.md
website/docs/getting-started/options/isolatedModules.md
website/docs/getting-started/options/tsconfig.md
website/docs/getting-started/options/useESM.md
website/docs/guides/esm-support.md
website/versioned_docs/version-29.0/getting-started/options.md
website/versioned_docs/version-29.0/getting-started/options/astTransformers.md
website/versioned_docs/version-29.0/getting-started/options/babelConfig.md
website/versioned_docs/version-29.0/getting-started/options/compiler.md
website/versioned_docs/version-29.0/getting-started/options/diagnostics.md
website/versioned_docs/version-29.0/getting-started/options/isolatedModules.md
website/versioned_docs/version-29.0/getting-started/options/tsconfig.md
website/versioned_docs/version-29.0/getting-started/options/useESM.md
website/versioned_docs/version-29.0/guides/esm-support.md

Closes #3828 
Green CI
**N.A.**

docs(devs-infra): add example transform match file regex

---

e2e/__tests__/native-esm-ts.test.ts
e2e/native-esm-ts/__tests__/native-esm-ts.spec.ts
e2e/native-esm-ts/jest-isolated.config.js
e2e/native-esm-ts/jest.config.js
e2e/native-esm-ts/package.json
e2e/native-esm-ts/quadruple/calculate.ts
e2e/native-esm-ts/quadruple/index.ts
e2e/native-esm-ts/tsconfig.json
src/config/paths-to-module-name-mapper.spec.ts
src/config/paths-to-module-name-mapper.ts
website/docs/getting-started/paths-mapping.md

ESM requires imported file's extension (e.g. `import foo from './foo.js'` instead of `import foo from './foo'`).
This is also true for typescript modules. They should be imported as `.js`, not `.ts`.
But jest does not have an "automatic typescript import extension mismatch detection for ESM". Rather, it lets users configure `moduleNameMapper` by themselves.
Currently, `pathsToModuleNameMapper` does not support this. 
Thus, a new option `removeJsExtension` is added.
This is not a breaking change.
Test code is provided as well. 
Thanks for maintaining ts-jest :)

feat: add `removeJsExtension` to `pathsToModuleNameMapper`

---

e2e/__tests__/__snapshots__/native-esm-js.test.ts.snap
e2e/__tests__/extend-ts-jest.test.ts
e2e/__tests__/native-esm-js.test.ts
e2e/__tests__/native-esm-ts.test.ts

test(e2e): change esm nodejs condition to 14.15.0

---

website/docs/getting-started/paths-mapping.md
website/versioned_docs/version-26.5/getting-started/paths-mapping.md
website/versioned_docs/version-27.0/getting-started/paths-mapping.md
website/versioned_docs/version-27.1/getting-started/paths-mapping.md
website/versioned_docs/version-28.0/getting-started/paths-mapping.md
website/versioned_docs/version-29.0/getting-started/paths-mapping.md

Hi! I'm a newcomer to ts-jest, had a problem setting up test environment for my project using this library.
TypeScript Alias using tsconfig.json didn't work in test files. 
I was wondering for around 30 minutes and found the answer from the [Issue's comment](https://github.com/kulshekhar/ts-jest/issues/364) - which was at the bottom of the page. It seemed really hard to find the information.
This PR provides "helper" part of "Paths Mapping" documentation page the missing code.
As this [Issue's comment](https://github.com/kulshekhar/ts-jest/issues/364#issuecomment-900349786) states, the documentation should state as follows to make jest config work with aliases from tsconfig:
```js
module.exports = {
// [...]
roots: ['<rootDir>'],
modulePaths: [compilerOptions.baseUrl], // <-- This will be …
```

docs(paths-mapping): Fixed broken guide for paths mapping helper

---

src/legacy/ts-jest-transformer.spec.ts
src/legacy/ts-jest-transformer.ts

When creating two instances of `TsJestTransformer` with different ts-jest configurations, they will generate the same config set if provided with the same options.
```js
const tr1 = new TsJestTransformer({ isolatedModules: true });
const tr2 = new TsJestTransformer({ isolatedModules: false });
// @ts-expect-error testing purpose
const cs1 = tr1._configsFor({ config: { cwd: process.cwd() }, cacheFS: new Map() } as TransformOptionsTsJest);
// @ts-expect-error testing purpose
const cs2 = tr2._configsFor({ config: { cwd: process.cwd() }, cacheFS: new Map() } as TransformOptionsTsJest);
console.log(cs1 === cs2); // true
```
This PR aims to fix this by taking into account the provided `tsJestConfig` when generating the cache key.
Tested on a project using `ts-jest`. Checked with `npm run …

fix(transformer): don't use cache when tsJestConfig is different

---

e2e/__tests__/__snapshots__/enum.test.ts.snap
examples/react-app/jest-esm-isolated.config.js
examples/react-app/jest-esm.config.js
examples/react-app/jest-isolated.config.js
package-lock.json
src/legacy/compiler/ts-jest-compiler.spec.ts

This adds some minor changes that will allow the jest 29.5 updates in #3979 to pass unit tests:
* Use mockImplementation instead of mockReset on Jest spy mock. The [jest implementation has changed](https://github.com/facebook/jest/pull/13692), and mockReset no longer sets an empty mock function on spy mocks.
* Update the snapshots for the e2e enum tests. A line number in the stack traces has changed.
* Update the caniuse-lite version. browserlist was writing a 'Browserslist: caniuse-lite is outdated...' message to stderr, which caused parsing of jest output to fail in the e2e transform-js test.
* Fix the configuration of jest transforms in the examples tests. These configurations previously specified two regex configurations that matched .ts and .tsx files (`^.+\\.(ts|tsx)$` and …

test: unit test fixes for jest 29.5

---

src/utils/importer.spec.ts

The importer test used untyped parameters in the mocks for `requireModule` and `resolveModule`. TypeScript 4.9 complains about this since those parameters are used to test for key membership in an object (`mod in modules`), and type `unknown` can't be used as an index.
It does a similar thing for patchers. Since the argument there is used with a spread operator, TypeScript 4.9 complains if it isn't an object.
Also removed a `!` non-null assertion for the `modules` variable and a cast to `any` for `requireModule`, since they aren't necessary.
This should fix the test failures in #4011 (update typescript to 4.9.5).

test: fix up types in importer.spec.

---

e2e/__tests__/custom-compiler.test.ts
package-lock.json
package.json
src/legacy/compiler/ts-compiler.spec.ts
src/legacy/config/config-set.spec.ts
src/transformers/hoist-jest.ts
src/utils/version-checkers.spec.ts
src/utils/version-checkers.ts
website/package-lock.json
website/package.json

Support typescript@5
- Update typescript version in
- devDependencies
- peerDependencies and `ExpectedVersions` enum
-  `website` folder  package.json
- added a casting on transformer function inside `src/transformers/hoist-jest.ts`. Error might being caused by [TS internal API changes](https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-50)
> The VisitResult type is no longer undefined by default; if you have written VisitResult<Node>, you may need to rewrite it as VisitResult<Node | undefined> to reflect that your visitor may return undefined.
> Visitor-using APIs now correctly reflect the type of the output, including whether it passed a given type guard test, and whether or not it may be undefined. In order to get the type you expect, you may need to pass a …

build(deps): update dependency typescript to v5

---

website/versioned_docs/version-29.0/getting-started/installation.md

docs: fix link

---

src/legacy/ts-jest-transformer.ts

Fixes #4207
Copied the changed code into the repo from https://github.com/jestjs/jest/issues/14719 and verified the error is correctly displayed.
I don't have time to write an actual unit test for this, so if that's needed to merge that contribution will have to come from somebody else 😅 
Ignore whitespace when looking at the diff: https://github.com/kulshekhar/ts-jest/pull/4226/files?w=1
Also, should enable: https://eslint.org/docs/latest/rules/no-async-promise-executor

fix: correct error handling in `processAsync`

---

e2e/__tests__/__snapshots__/native-esm-js.test.ts.snap
e2e/__tests__/extend-ts-jest.test.ts
e2e/__tests__/native-esm-js.test.ts
e2e/__tests__/native-esm-ts.test.ts
e2e/run-jest.ts

Since we support only Node 16+, we can safely remove this function
Green CI
**N.A.**

test(e2e): remove `onNodeVersions` function

---

src/legacy/ts-jest-transformer.spec.ts
src/legacy/ts-jest-transformer.ts

`ts-jest` will generate different transformations if `supportsStaticESM` is true or false. I've noticed the issue when using jest with an esm globalSetup file in my application AND my tests were re-using imported files from the globalSetup.
`globalSetup` file seems is transpiled with `supportsStaticESM` unset here https://github.com/jestjs/jest/blob/4e56991693da7cd4c3730dc3579a1dd1403ee630/packages/jest-transform/src/ScriptTransformer.ts#L781
While tests had `supportsStaticESM` true in my case, and therefore, generating two different outputs.

fix: calculated cache key based on supportsStaticESM

---

src/legacy/ts-jest-transformer.spec.ts
src/legacy/ts-jest-transformer.ts

I noticed that running ts-jest was very slow in one of my projects so I dig a little into why and noticed the performance bottleneck comes from the `getCacheKey` function and in particular the `writeFileSync` that is being called to store the dependency graph.
Writing this file is what's taking most of the time in this process as the content we write is very heavy : the whole file content and its resolved module names.
I ran a few tests on a project with different configurations and here are the result:
| Case | 1st run (clean jest cache) | 2nd run (with jest cache)
|---|----|----|
|Current ts-jest (Writing dependency graph file) | 218s | 16s|
|No cache (`--no-cache`) | 44s | 44s|
|This PR version (No dependency graph file) | 47s | 14s|
As we can see from the results, the fastest way to …

perf: remove ts resolved module cache file

---

package.json

https://github.com/kulshekhar/ts-jest/blob/edef16ed78fb114fbeb93953660b397cffa9ba18/src/types.ts#L1
The above import means when using TypeScript there is a dependency on `@jest/transform` which is currently not expressed, making Yarn Berry unhappy when using the PnP linker.
From what I understand, specifying this dependency as an optional peer dependency should resolve this.

fix: add `@jest/transform` as an optional peer dependency

---

src/constants.ts
src/legacy/ts-jest-transformer.spec.ts

This is a pull request to implement the feature request:
[Support loading of ".cjs" and ".cts" files. #3996](https://github.com/kulshekhar/ts-jest/issues/3996)
Closes #3996 
I added 2 test cases to `src/legacy/ts-jest-transformer.spec.ts` to test loading of '.cts' and '.cjs' files.
`npm run test` reports:
```
Test Suites: 35 passed, 35 total
Tests:       329 passed, 329 total
Snapshots:   135 passed, 135 total
```
`npm run test-examples` also exited successfully.
This fix will allow us to remove our hack we've been using in order to transform `.cts` files and load `.cjs` files.

fix(transformer): allow transforming of .cts/.mts extensions. (#3996)

---

src/cli/cli.spec.ts
src/cli/config/init.ts

[Installation guide](https://kulshekhar.github.io/ts-jest/docs/getting-started/installation) does not work out of the box. `npx ts-jest config:init` does not respect `"type": "module"` in `package.json`, causing `npx jest` to fail. This PR makes `config:init` sensitive to this case.
[Screencast from 2023-09-30 12-29-34.webm](https://github.com/kulshekhar/ts-jest/assets/30221758/cca566b1-da5c-4652-8a3c-6a90079bfc28)
Closes #4012

feat(cli): `config:init` makes mjs config when using ESModules

---

package-lock.json
package.json

Per the npm install message:
> npm warn deprecated @types/rimraf@4.0.5: This is a stub types definition. rimraf provides its own type definitions, so you do not need this installed.

Remove deprecated @types/rimraf

---

src/types.ts

revert: allow `babelConfig` in default/js-with-ts presets

---

package.json

Dependency ejs was installing as dependency of ts-jest as vulnerable version 3.1.9 ([CVE-2024-33883](https://nvd.nist.gov/vuln/detail/CVE-2024-33883)). Patched version is 3.1.10
Fixes #4450 
Ran build and tests, which run successfully.

build(deps): Update dependency ejs to ^3.1.10

---

e2e/__tests__/native-esm-ts.test.ts
e2e/native-esm-ts/__tests__/third-party.spec.ts
e2e/native-esm-ts/package-lock.json
e2e/native-esm-ts/package.json
e2e/native-esm-ts/third-parties/dirname-filename-esm.ts
e2e/native-esm-ts/third-parties/i18next-fs-backend.ts
src/legacy/compiler/ts-compiler.spec.ts
src/legacy/compiler/ts-compiler.ts

See commit
Fixes #4468 
Fixes #4473 
Green CI
**N.A.**

fix: revert support implementation for `Node16/NodeNext`

---

website/docs/getting-started/installation.md
website/versioned_docs/version-26.5/getting-started/installation.md
website/versioned_docs/version-27.0/getting-started/installation.md
website/versioned_docs/version-27.1/getting-started/installation.md
website/versioned_docs/version-28.0/getting-started/installation.md
website/versioned_docs/version-29.0/getting-started/installation.md
website/versioned_docs/version-29.2/getting-started/installation.md

closes #4496
In the installation doc page, the link that goes to ts-jest options is broken and redirects to the "options" folder instead of redirecting to the options.md file.
- Manually checked if the broken link was fixed
- Manually checked if links that goes to options/*.md works in the page options.md
- Ran lint

docs(installation): fix broken options.md internal link

---

website/docs/getting-started/paths-mapping.md
website/versioned_docs/version-29.2/getting-started/paths-mapping.md

As noted in this commend:
https://github.com/jestjs/jest/issues/11644#issuecomment-1171646729
And this comment:
https://github.com/kulshekhar/ts-jest/issues/1107#issuecomment-559759395
Insufficient documentation for `tsconfig` `paths` option
Documentation only

Update `paths-mapping.md` for global setup files

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [ts-jest Guru](https://gurubase.io/g/ts-jest) to Gurubase. ts-jest Guru uses the data from this repo and data from the [docs](https://kulshekhar.github.io/ts-jest) to answer questions by leveraging the LLM.
In this PR, I showcased the "ts-jest Guru", which highlights that ts-jest now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if …

Introducing ts-jest Guru on Gurubase.io

---

src/legacy/compiler/__snapshots__/ts-compiler.spec.ts.snap
src/legacy/compiler/ts-compiler.spec.ts
src/legacy/compiler/ts-compiler.ts

`customConditions` is only available to `Node16`/`NodeNext`/`Bundler` module option, see https://www.typescriptlang.org/tsconfig/#customConditions
Fixes #4620
Green CI
**N.A.**

fix: set `customConditions` to `undefined` in `TsCompiler`

---

.github/actions/setup-workspace/action.yml

All caches restored from `restore-keys` in [`.github/actions/setup-workspace/action.yml`](https://github.com/kulshekhar/ts-jest/blob/12949188017939aa83e9a5dbd4a091211e1816f4/.github/actions/setup-workspace/action.yml#L23-L24) are discarded, so this option is not needed.
`cache-hit` has three possible values: [[1]](https://github.com/actions/cache?tab=readme-ov-file#outputs) [[2]](https://github.com/actions/cache/pull/1514/files) [[3]](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#output-parameters-for-the-cache-action) 
* `'true'` if there's an exact match for `key`.
* `'false'` if some prefix of the key matches an entry in `restore-keys`.
* `''` otherwise.
In the `cache-hit = false` case, `node_modules` is …

build: Remove `restore-keys` from `.github/actions/setup-workspace/action.yml`

---

.github/actions/setup-workspace/action.yml

This change resolves #4749 by configuring `actions/setup-node` to cache packages.
Example config using these options [[1]](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data):
```yaml
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: '14'
cache: 'npm'
cache-dependency-path: '**/package-lock.json'
- run: npm ci
- run: npm test
```
* [`--prefer-offline`](https://docs.npmjs.com/cli/v11/using-npm/config#prefer-offline) documentation.
If CI succeeds, we should be good to go.

build: Add NPM cache

---

src/legacy/config/__snapshots__/config-set.spec.ts.snap
src/legacy/config/config-set.spec.ts
src/legacy/config/config-set.ts

Fixes #4847 
Green CI
**N.A.**

fix(config): disable `isolatedDeclarations`
