kulshekhar/ts-jest

- index.js
- package.json
- preprocessor.js
- tests/__tests__/button.test.js
- tests/button/Button.tsx
- tests/button/__tests__/Button.test.tsx
- tests/button/__tests__/__snapshots__/Button.test.tsx.snap
- tests/button/package.json
> Use correct tsc compiler option  values

- package.json
- tests/__helpers__/runJest.ts
- tests/__helpers__/utils.ts
- tests/__tests__/ts-compilation.spec.ts
- tests/__tests__/ts-errors.spec.ts
- tests/__tests__/tsconfig-default.spec.ts
- tests/__tests__/tsconfig-inline.spec.ts
- tests/__tests__/tsconfig-string.spec.ts
- tests/__tests__/tsx-compilation.spec.ts
- tests/__tests__/tsx-errors.spec.ts
- tests/__ts-jest-mocks__/path.ts
- tests/button/__mocks__/ts-jest.ts
- tests/button/tsconfig.json
- tests/simple/__mocks__/ts-jest.ts
- tests/simple/tsconfig.json
- tests/tsconfig-test/__mocks__/ts-jest.ts
- tests/tsconfig.json
Implementing #17.
I've also changed jest config for root project in order to avoid running inner tests that are made for integration testing.
> #17 minimal config for testing with TS.

- AUTHORS
- README.md
- package.json
@kulshekhar  I'm very grateful that you mentioned me as one of [Authors](https://github.com/kulshekhar/ts-jest/blob/master/AUTHORS), so I've improved this mention a little bit. If you think that this is acceptable just merge it, if not - reject.
Anyway thanks for your approval of our work 😉
> Authors patch

- .travis.yml
- README.md
Due to [this issue](https://github.com/kulshekhar/ts-jest/issues/32#issuecomment-255817691)
> Use travis 

- .travis.yml
- package.json
- tests/__tests__/ts-coverage.spec.ts
Implemented basic support for #36 and ci builds on travis.
> Travis-ci fix for node4

- src/default-retrieve-file-handler.ts
- src/default-retrieve-map-handler.ts
- src/index.ts
- src/retrieve-sourceMap-url.ts
- src/transpile-if-ts.ts
> Revert "Removing handlers for source-map-support."

- appveyor.yml
- scripts/tests.js
Temporary fix for #53 omitting some tests on AppVeyor.
> Temporary fix for #53 omitting some tests on AppVeyor.

- README.md
- tests/__tests__/import.spec.ts
- tests/imports-test/__tests__/absolute-import.test.ts
- tests/imports-test/__tests__/classes/Hello-relative.test.ts
- tests/imports-test/__tests__/classes/Hello.test.ts
- tests/imports-test/__tests__/relative-import.test.ts
- tests/imports-test/package.json
- tests/imports-test/src/absolute-import.ts
- tests/imports-test/src/classes/Hello.ts
- tests/imports-test/src/relative-import.ts
- tests/imports-test/tsconfig.json
> Absolute path imports

- package.json
- scripts/tests.js
- src/coverageprocessor.ts
- src/utils.ts
- tests/button/node_modules/ts-jest.js
- tests/simple-async/node_modules/ts-jest.js
- tests/simple/node_modules/ts-jest.js
- tests/use-strict/node_modules/ts-jest.js
- tests/watch-test/node_modules/ts-jest.js
[CHANGELOG](https://github.com/facebook/jest/blob/b0396be/CHANGELOG.md)
> Update for jest@18

- README.md
https://github.com/kulshekhar/ts-jest/issues/92
> Add installation steps for React Native in README

- .travis.yml
> Increase the watch limit in travis

- scripts/tests.js
These were excluded earlier due to #89
> Enable async tests

- package.json
Closes https://github.com/kulshekhar/ts-jest/issues/108.
> Add dependencies on `jest-util` and `jest-config`

- README.md
- package.json
- src/utils.ts
- tests/__tests__/tsconfig-comments.spec.ts
- tests/tsconfig-test/allows-comments.json
- tsconfig.json
> Allow comments in tsconfig.json

- src/coverageprocessor.ts
- tests/__helpers__/runJest.ts
> Create cache directory if it doesn't exist

- README.md
See https://stackoverflow.com/questions/41188484/jest-typescript-ts-jest-coverage-is-slightly-incorrect
P.S. I'm not good at documenting stuff, if you have any corrections - I will be happy to add them.
> Add note about remapped coverage reports directory

- src/utils.ts
- tests/__tests__/tsconfig-default.spec.ts
- tests/__tests__/tsconfig-inline.spec.ts
- tests/__tests__/tsconfig-string.spec.ts
> Set inlineSourceMap to true unless it has been set to false

- package.json
- src/utils.ts
> Set module to commonjs if it isn't set

- src/coverageprocessor.ts
- tests/__tests__/ts-coverage.spec.ts
- tests/simple/.gitignore
- tests/simple/with-coverage-dir.json
> Coverage text writer

- README.md
> Add note about the fix for long paths

- README.md
> Adds completed jest setup for react native

- README.md
- package.json
- src/utils.ts
> fix: remove outDir when collecting coverage

- package.json
- src/preprocessor.ts
To fix [this issue](https://github.com/kulshekhar/ts-jest/pull/202#issuecomment-300020026)
> Use Jest Config to obtain collectCoverage value

- README.md
This describes a better RN setup with working sourcemaps, as discussed in #209
> Updated readme with a better React Native configuration

- src/jest-types.ts
- src/preprocessor.ts
- tests/__tests__/get-cache-key.spec.ts
> Implement getCacheKey to invalidate jest cache when tsconfig changes

- AUTHORS
- README.md
> Updated README 📖

- .travis.yml
- appveyor.yml
Test with Node v8 instead of v7
> Test with Node v8 instead of v7

- .travis.yml
- appveyor.yml
- package.json
- src/default-retrieve-file-handler.ts
- src/index.ts
- src/jest-types.ts
- src/postprocess.ts
- src/preprocessor.ts
- src/transpile-if-ts.ts
- src/utils.ts
- tslint.json
> Fix tslint errors and run tslint in CI

- AUTHORS
- package.json
Just adding myself to contributors/authors and putting them in alphabetical order
> add bcruddy to the authors file and contributors section

- README.md
- package.json
> Support prerelease version of Jest 21

- AUTHORS
- README.md
see also https://github.com/Microsoft/TypeScript/issues/5243
#112
> Add note re const enum to README

- AUTHORS
- package.json
- src/utils.ts
- tests/__tests__/tsconfig-default.spec.ts
- tests/__tests__/tsconfig-inline.spec.ts
- tests/__tests__/tsconfig-string.spec.ts
> Always remove outDir while computing TypeScript Config for transpiling

- README.md
Reverts kulshekhar/ts-jest#313
> Revert "Adding info about limitations in debugger statements in README"

- appveyor.yml
- package.json
- yarn.lock
To release the changes from #287
Edit: the changes in appveyor configuration (to fix some weird build issues), this also closes #321
> Bump version to 21.0.1

- .travis.yml
for [greenkeeper](https://github.com/greenkeeperio/greenkeeper-lockfile) PRs
Fixes #328
> Configure travis to update yarn.lock files

- package.json
- src/utils.ts
> Find tsconfig.json by traversing up

- AUTHORS
- README.md
Just spend the night trying to make paths work, to in end all needed is "moduleNameMapper".
I'm just adding a this to help who has the same problems.
Hope this helps!
> Advice about setting up module path mappings

- AUTHORS
- README.md
- index.js
- package.json
- src/index.ts
- src/preprocessor.ts
- tests/__tests__/transpile-if-ts.spec.ts
- tests/jestconfig-test/jest.json
Reverts kulshekhar/ts-jest#363
fixes #367
> Revert "Change the package entry point to preprocessor.js itself"

- README.md
> Update usage of moduleFileExtensions

- .travis.yml
- package.json
- yarn.lock
> Pin versions of fs-extra and its types

- README.md
to avoid issues like #386 and #390
closes #386
> Add a note about processing javascript files

- AUTHORS
- README.md
I found this confusing so I took the wording from #327, customized it for context and added it to the `README` to avoid future confusion.
> Clarify warning

- AUTHORS
- CHANGELOG.md
I think it's better to have a changelog file to list down all the changes every release. So everyone can just go there and read it easily. At the moment I only write the changelog starting from v22.0.0. I need help from others to complete it.
> Add CHANGELOG.md for documentation new changes every release

- package.json
- src/preprocessor.ts
- src/utils.ts
- tests/__tests__/tsconfig-default.spec.ts
- tests/__tests__/tsconfig-string.spec.ts
- yarn.lock
fixes #455 
*didn't dive deep into this*
> Continue relying on only inline sourcemaps

- package.json
- src/utils.ts
> Use os separator instead of hard-coding it

- src/postprocess.ts
Implements #530.  Is the code style ok?  Should I move anything around?
> Import babel deps on-demand, skipping if skipBabel is true

- src/utils.ts
- tests/__tests__/transpile-if-ts.spec.ts
- tests/__tests__/ts-diagnostics.spec.ts
simplify how tsconfig is read and parsed.
> refactor: clean up reading of configuration

- package.json
> chore(package): update @types/react to version 16.3.16

- package.json
> chore(package): update @types/react to version 16.4.1

- package.json
- src/transpiler.ts
- src/utils.ts
- tests/__tests__/jest-projects-with-workspace.spec.ts
- tests/__tests__/transpiler.spec.ts
- tests/jest-projects-with-workspace/package.json
- tests/jest-projects-with-workspace/packages/bar/package.json
- tests/jest-projects-with-workspace/packages/bar/src/index.ts
- tests/jest-projects-with-workspace/packages/bar/test/index.test.ts
- tests/jest-projects-with-workspace/packages/bar/tsconfig.json
- tests/jest-projects-with-workspace/packages/foo/package.json
- tests/jest-projects-with-workspace/packages/foo/src/index.ts
- tests/jest-projects-with-workspace/packages/foo/test/index.test.ts
- tests/jest-projects-with-workspace/packages/foo/tsconfig.json
- yarn.lock
Includes contributions from @cspotcode and @js-um 
Combining into a single PR to avoid having to update the 5-6 PRs each time one is merged
> Combine prs

- src/transpiler.ts
- tests/__tests__/transpiler.spec.ts
> Reopening #533: Catch syntax errors even when calling transpileModule

- package.json
> chore(package): update @types/react to version 16.4.6

- package-lock.json
- src/utils.ts
- tests/__tests__/tsconfig-default.spec.ts
- tests/__tests__/tsconfig-string.spec.ts
I had issues when combination of 
```
"declaration": true,
"declarationMap": true,
```
Was giving below error:
```
TypeScript compiler encountered syntax errors while transpiling. Errors: Option 'declarationMap' cannot be specified without specifying option 'declaration'.
at createTranspilationError (node_modules/ts-jest/src/transpiler.ts:56:12)
at transpileViaTranspileModule (node_modules/ts-jest/src/transpiler.ts:44:11)
at Object.transpileTypescript (node_modules/ts-jest/src/transpiler.ts:14:27)
at process (node_modules/ts-jest/src/preprocessor.ts:51:27)
at Object.process (node_modules/ts-jest/index.js:8:51)
```
Above PR will also fix  #593
> make sure that declaration is disabled

- src/postprocess.ts
It fixes #627, but AFAIK there is badly no way of doing a test for that, and yeah it's an ugly hack but it works.
Babel issue: https://github.com/babel/babel/issues/6577
> [FIX] hack for babel 6 so that breakpoints do work

- README.md
- link to the new [slack channel](https://join.slack.com/t/ts-jest/shared_invite/enQtNDE1ODQ0OTEzMTczLWU2ZTk5YTMzYTE1YjBkZTk5ODI1NWU3NWU0NzhlOWJlZDNkYTRlM2Y3NWQ1YWVjMjc5Mjg1NmY1NTdkNWQ3MTA)
- link to beta instructions (#697)
This PR doesn't need a release/publish (except if we want the readme updated on npm too).
> adds links to slack and beta in readme (master)

- docs/_data/nav.yml
- docs/index.md
- docs/user/react-native/index.md
published temporally [there](https://huafu.github.io/ts-jest/user/react-native/)
> [beta] adds React Native docs

- e2e/__templates__/default/package-lock.json
> Fix security vulnerability

- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-6/package-lock.json
- e2e/__templates__/with-babel-6/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-jest-22/package-lock.json
- e2e/__templates__/with-jest-22/package.json
- e2e/__templates__/with-typescript-2-7/package-lock.json
- e2e/__templates__/with-typescript-2-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- package-lock.json
- package.json
This upgrades all packages at once and will flush all failing dependabot (there might have been an issue with the lock file)
It's also upgrading package-locks of E2E test cases.
> Upgrade packages

- docs/user/config/index.md
> Path mappings require baseUrl property

- README.md
> Correct Spelling Error in Readme

- src/compiler.ts
Internally, TypeScript paths are represented with '/' as the directory separator, which results in cache misses in `src\compiler.ts` and storing file content in the cache twice. This fix normalizes the path to resolve the issue. Fixes https://github.com/kulshekhar/ts-jest/issues/1132.
> fix: typescript serviceHost cache miss on Windows operating systems

- src/cli/cli.spec.ts
tests in src/cli/cli.spec.ts were not running
> test: removed async from describes

- src/transformers/hoist-jest.spec.ts
- src/transformers/hoist-jest.ts
> fix(transformers): hoist jest.enableAutomock and jest.disableAutomock

- src/util/importer.ts
> fix: use correct typescript package in yarn workspaces

- package-lock.json
- package.json
> fix: add jest-config to dependencies list

- e2e/__templates__/default/package.json
- package-lock.json
> Upgrade vulnerable deps

- .github/ISSUE_TEMPLATE/bug.md
> chore: fix bug template not appearing

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/regression.md
Bring back debug log session from the old issue template to bug/regression issue template
**N.A.**
**N.A.**
> chore: enhance bug and regression template with debug log session

- package-lock.json
- package.json
- src/__helpers__/fakers.ts
- src/cli/config/migrate.ts
- src/compiler/compiler-utils.ts
- src/config/config-set.spec.ts
- src/config/config-set.ts
- src/shims.d.ts
- src/ts-jest-transformer.ts
- src/types.ts
- Upgrade `@commitlint/config-conventional`, `fast-json-stable-stringify`, `@jest/types`, `@jest/transform`.
- Correct a few typings.
Green CI
**N.A.**
> chore: upgrade dependencies, correct typings

- package-lock.json
- package.json
Restores `node@8` support, since `mkdirp@1` requires node 10 or higher.
Run the tests, see if they fail.
It's an unbreaking change :)
Fixes #1550
> chore(deps): use `mkdirp@0.x`

- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- e2e/__tests__/__snapshots__/source-map.test.ts.snap
- e2e/__tests__/source-map.test.ts
Update e2e dependencies
Green CI
**N.A.**
> chore: update e2e dependencies

- CHANGELOG.md
Update `CHANGELOG` of **25.5.0-alpha.0** for master branch, so user knows we have an alpha release
Green CI
**N.A.**
> chore: update CHANGELOG.md for 25.5.0-alpha.0

- package-lock.json
- package.json
Remove `resolve` dependency since it's not in used by the codes
Green CI
**N.A.**
> chore: remove resolve dependency

- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- e2e/__tests__/__snapshots__/hoisting.test.ts.snap
A core task to update dependencies for e2e templates 
Green CI
**N.A**
> test: update e2e templates' dependencies

- docs/user/config/index.md
The current example won't actually work, as TypeScript doesn't let you type `module.exports` (there's an issue open for it somewhere, but can't seem to find it right now), and the `@type` must be "on" the variable it's typing.
None
Note the lack of TS error about the assignment of non-string to what should be type string.
Likewise note the lack of complaining about `improveMocks`.
Note that WebStorm does use the `@types` in this position to give property autocomplete advice, but won't tell you about invalid properties.
> docs: update IDE configuration example

- CHANGELOG.md
- package-lock.json
- package.json
- Updated version in `package.json` to **26.0.0**
- Adjusted `CHANGELOG.md`
- Set `mkdirp` to **1.x** as dropping support node 8
- Limit `eslint` at **6.x** because **7.x** complains about peerDependency warning with `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser`
Green CI
**N.A.**
> chore(release): 26.0.0

- package-lock.json
- package.json
Update `@jest/transform` and `@jest/types` to **26.x**
Green CI
**N.A.**
> build(deps-dev): bump @jest/transform to 26.x, @jest/types to 26.x

- package.json
- src/types.ts
Close #1666 
Test against the repo in #1666 
Also lock `typescript` at 3.x in `package.json`
> fix(typing): don't mark BabelConfig as internal type

- .eslintrc.js
- src/cli/helpers/presets.ts
- src/compiler/compiler-utils.ts
- src/compiler/instance.ts
- src/compiler/language-service.ts
- src/compiler/transpiler.ts
- src/config/config-set.spec.ts
Disable rule `@typescript-eslint/no-non-null-assertion` is bad. We should leave it enable
Green CI, no lint warnings
**N.A.**
> chore(dev-infra): enable rule @typescript-eslint/no-non-null-assertion

- .eslintrc.js
- e2e/__helpers__/test-case/run-descriptor.ts
- e2e/__helpers__/test-case/run-result.ts
- e2e/__helpers__/test-case/runtime.ts
- e2e/__helpers__/test-case/utils.ts
- e2e/__serializers__/run-result.ts
- e2e/__tests__/logger.test.ts
- scripts/test-external-project.js
- scripts/update-e2e-templates.js
- src/__helpers__/source-maps.ts
- src/config/config-set.spec.ts
- src/config/config-set.ts
- src/ts-jest-transformer.spec.ts
- src/util/version-checkers.spec.ts
When upgrading eslint and typescript-eslint, I had to disable this rule. Since this rule is in eslint recommended, we should enable it back.
Green CI
**N.A.**
> chore(dev-infra): enable rule restrict-template-expressions

- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- e2e/__tests__/__snapshots__/logger.test.ts.snap
- e2e/__tests__/logger.test.ts
Close #1687 
Green CI
**N.A.**
> chore(dev-infra): fix failed e2e test, update e2e templates

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.1.0

- docs/user/config/index.md
Add missing markdown reference for `astTransformers` in documentation
Doc page should display properly the option `astTransformers`
**N.A.**
> chore(docs-dev): add missing markdown reference for `astTransformers`

- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
Update dependencies for e2e
Green CI
**N.A.**
> chore(deps-dev): update dependencies for e2e

- e2e/__helpers__/test-case/types.ts
- e2e/__tests__/logger.test.ts
- src/compiler/__snapshots__/language-service.spec.ts.snap
- src/compiler/__snapshots__/transpiler.spec.ts.snap
- src/compiler/language-service.spec.ts
- src/compiler/transpiler.spec.ts
- src/config/config-set.ts
- Added unit tests for source map with/without `mapRoot`
- Correct e2e typings
- Reorganize some test cases
Green CI
**N.A.**
> test: add additional unit tests for source map, correct e2e typings

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.1.1

- src/compiler/__snapshots__/transpiler.spec.ts.snap
- src/compiler/language-service.spec.ts
- src/compiler/transpiler.spec.ts
Remove unnecessary `writeFileSync` and `removeSync` for some unit tests in `compiler` area.
Green CI
**N.A.**
> test: improve unit test speed for compiler tests

- src/compiler/compiler-utils.ts
- src/compiler/instance.ts
- src/ts-jest-transformer.ts
Use `stringify` util function from json util instead of `JSON.stringify`.
Green CI
**N.A.**
> chore(devs-infra): use stringify from json util

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/dependency/package.json
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- src/types.ts
- Update e2e templates' dependencies
- Slightly adjust typing in `types.ts`
Green CI
**N.A.**
> chore(dep-devs): update e2e templates dependencies

- src/compiler/language-service.ts
Add an undefined checked for `realpath` of `LanguageService`
Green CI
**N.A.**
> chore(devs-infra): remove ! on realpath of LanguageService

- src/config/config-set.ts
- src/types.ts
Expose `compilerModule` from `ConfigSet` as public API. This is needed because custom AST transformers are using it.
Green CI.
**N.A.**
> chore(typings): expose compilerModule and TTypeScript as public typings

- e2e/README.md
Update outdated e2e `README.md`
> build(docs-infra): update e2e README.md

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.1.2

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.1.3

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
Upgrade e2e dependencies
Green CI
**N.A.**
> test(e2e): upgrade e2e dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.1.4

- CHANGELOG.md
- package-lock.json
- package.json
- src/__mocks__/thing.spec.ts
- src/compiler/__snapshots__/language-service.spec.ts.snap
- src/compiler/language-service.spec.ts
- src/compiler/language-service.ts
> Merge v26.1.4

- src/config/config-set.ts
Other getters have been memoized, no idea why this one I didn't do it. This PR makes it as a memoized getter.
Green CI
**N.A.**
> chore(devs-infra): memoize `isTestFile` in config-set

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
Update e2e templates' dependencies
Green CI
**N.A.**
> build(devs-dep): update e2e templates' dependencies

- src/config/config-set.spec.ts
- src/index.ts
- src/types.ts
- Mark `version`/`digest` in `index.ts` as internal
- Mark `TsJestConfig` as internal
Green CI
**N.A.**
> refactor(devs-infra): mark a few typings as internal

- docs/user/config/index.md
Correct type of `astTransformers` in documentation to `object` instead of `string[]`
Green CI
**N.A.**
> docs(devs-infra): correct astTransformers type

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- package-lock.json
Update e2e templates
Green CI
**N.A.**
> build(deps-dev): update e2e templates' dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.3.0

- tsconfig.build.json
Enable `removeComment` for `tsconfig.build.json`. Our codes' comments shouldn't be shipped to end users.
Green CI
**N.A.**
> build(devs-infra): remove comments for build assets

- src/config/config-set.ts
- src/presets/__snapshots__/index.spec.ts.snap
- src/presets/index.spec.ts
Create a private method to make config option object for `tsConfig`,  `packageJson` and `babelConfig`
Added missing unit test for `presets/index.ts`, green CI
**N.A.**
> refactor(config): improve resolving tsconfig, package.json, babel config

- .eslintrc.js
- docs/user/config/diagnostics.md
- scripts/test-external-project.js
- src/config/__snapshots__/config-set.spec.ts.snap
- src/config/config-set.spec.ts
- src/config/config-set.ts
The codes to resolve diagnostics are pretty hard to read and not type safety. This PR refactors to make it easier to read and stricter type safety.
Green CI
**N.A.**
> refactor(config): improve resolving diagnostics from jest config

- src/cli/index.ts
- src/config/config-set.spec.ts
- src/presets/index.spec.ts
- src/presets/index.ts
- src/transformers/path-mapping.spec.ts
- tsconfig.json
Enable `esModuleInterop` to get rid of import legacy syntax as well as reducing the need of using import * syntax
Green CI
**N.A.**
> build(devs-infra): enable esModuleInterop

- .github/dependabot.yml
Dependabot is now natively integrated in GitHub. This PR is to create a config file to follow GitHub convention.
No need to test
**N.A.**
> build(devs-infra): setup dependabot.yml

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.4.0

- README.md
We already migrated to native GitHub dependabot so the dependabot badge becomes useless. This PR is to remove the badge from `README.md`
The badge should not display in `README.md` anymore.
**N.A.**
> build(devs-infra): remove dependabot badge

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.4.1

- src/transformers/__snapshots__/path-mapping.spec.ts.snap
- src/transformers/path-mapping.spec.ts
Add missing import default, e.g. `import React from 'react'` for `path-mapping` transformer.
Green CI
**N.A.**
> test(transformers): add missing test case for import default

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
Upgrade e2e templates' dependencies
Green CI
**N.A.**
> build(deps-dev): upgrade e2e templates' dependencies

- e2e/__cases__/ts-jest-checks/index.spec.ts
- src/config/config-set.spec.ts
- src/config/config-set.ts
- Use `rootLogger` in constructor
- Remove constants `MY_VERSION`, getter `versions`
- Remove `@Memoize` for getter `cwd` and assign value in constructor
Green CI
**N.A.**
> refactor(config): refactor `ConfigSet`

- src/config/config-set.spec.ts
- src/config/config-set.ts
- Replace `jest` getter with private field `_jestCfg`
- Replace `rootDir` getter with private field `_rootDir`
Green CI
**N.A.**
> refactor(config): replace `jest`/`rootDir` getters with private fields

- e2e/__tests__/__snapshots__/logger.test.ts.snap
- e2e/__tests__/logger.test.ts
- src/compiler/instance.ts
- src/compiler/language-service.ts
- src/compiler/transpiler.ts
- src/config/__snapshots__/config-set.spec.ts.snap
- src/config/config-set.spec.ts
- src/config/config-set.ts
- src/constants.ts
- src/transformers/index.spec.ts
- src/ts-jest-transformer.ts
- src/types.ts
- Convert most of getters to private fields
- Optimize logic of mapping user config to internal config
- Expose a few getters as public apis
- Rename interface `TsJestConfig$diagnostics` to `TsJestDiagnosticsCfg`
- Change `CachedConfigSet` to cache transformerConfig string instead of object type
Readjusted some unit tests, most of unit tests are the same. Green CI
**N.A.**
> refactor(config): refactor `ConfigSet` class

- src/__helpers__/fakers.ts
- src/config/config-set.spec.ts
- src/config/config-set.ts
The PR #2050 accidentally removed the possibility to mock logging for testing. This PR is to bring back that feature.
Green CI
**N.A.**
> refactor(config): bring back possibility to mock logging in test

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.4.2

- e2e/__external-repos__/custom-typings/__tests__/index.test.ts
- e2e/__external-repos__/custom-typings/global.ts
- src/compiler/language-service.ts
Revert #2055 
Closes #2061
Green CI
**N.A.**
> fix(compiler): only exclude test files when initializing compiler

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 26.4.3

- README.md
- docs/index.md
> chore: redesign top part of README.md

- commitlint.config.js
- package-lock.json
- package.json
Switch commmit lint rule to `@commitlint/config-angular` which is better than `@commitlint/config-conventional`
no test required
**N.A.**
> build(devs-infra): use `@commitlint/config-angular`

- src/__helpers__/fakers.ts
- src/compiler/__snapshots__/language-service.spec.ts.snap
- src/compiler/__snapshots__/transpiler.spec.ts.snap
- src/config/config-set.ts
- tsconfig.json
Ship package with target `es2015`. This is more inline with jest, see https://jestjs.io/blog/2020/05/05/jest-26
Green CI
`ts-jest` no longer ships with `es5` build but now with `es2015`
**N.A.**
> build(devs-infra): build package with target `es2015`

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__serializers__/run-result.ts
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- package-lock.json
- package.json
- src/__serializers__/processed-source.ts
- src/compiler/language-service.spec.ts
Upgrade typescript to 4.1 for both project deps as well as e2e deps
Green CI
**N.A.**
> build(devs-infra): upgrade typescript to 4.1

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 27.0.0-alpha.1

- src/config/config-set.spec.ts
- tsconfig.build.json
- tsconfig.json
- tsconfig.spec.json
Revert #2130
Green CI
**N.A.**
> build(dev-infra): build package with target es5

- package-lock.json
- src/cli/config/init.ts
- src/cli/config/migrate.ts
Upgrade `@types/yargs`
Green CI
**N.A**
> build(devs-dep): upgrade @types/yargs

- .github/workflows/doc-generator.yml
- docs/src/css/custom.css
- docs/src/pages/index.js
Adjust `docs-generator` workflow to work with docusaurus
- docs-generator should be green
- `gh-pages` branch should be updated on every PR is merged into `master` branch
**N.A.**
> build(devs-infra): make doc-generator workflow work correctly

- docs/src/pages/index.js
Correct some mistakes on home page of doc
> docs(devs-infra): correct some mistakes on doc homepage

- docs/docs/presets.md
- e2e/__cases__/presets/ts-jest-presets.spec.ts
- e2e/__tests__/module-kinds/__snapshots__/es2015-esm.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/esnext-esm.test.ts.snap
- e2e/__tests__/module-kinds/es2015-esm.test.ts
- e2e/__tests__/module-kinds/esnext-esm.test.ts
- presets/index.js
- src/constants.ts
- src/presets/__snapshots__/create-jest-preset.spec.ts.snap
- src/presets/create-jest-preset.ts
Set all ESM options to true for ESM presets.
Adjusted tests, green CI
**N.A.**
> refactor(presets): set all ESM transform options true for ESM presets

- README.md
> docs(dev-infra): correct wrong link for README

- .github/workflows/release-and-publish.yml
- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 27.0.0-next.2

- .npmignore
- src/ts-jest-transformer.ts
- Set `compiler` to `protected`
- Exclude `website` from published assets
Green CI
**N.A.**
> build(devs-infra): set compiler to `protected` in `TsJestTransformer`

- README.md
- website/src/pages/index.js
Link directly to `testing` channel of `Reactiflux` in Discord for Jest for main `README` and docs homepage.
Clicking on the link should lead directly to `testing` channel in `Reactiflux` Discord.
**N.A.**
> docs(devs-infra): link directly to Reactiflux testing channel

- website/docs/migration.md
```
cv/packages/lib on  v2 [?] ❯ yarn create ts-jest config:mgirate jest.config.js
yarn create v1.22.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-ts-jest: Not found".
info If you think this is a bug, please open a bug report with the information provided in ".config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
```
cv/packages/lib on  v2 [?] ❯ yarn ts-jest config:migrate jest.config.js
yarn run v1.22.5
$ node_modules/.bin/ts-jest config:migrate jest.config.js
Migrated Jest configuration:
module.exports = {
roots: [
'<rootDir>',
],
preset: 'ts-jest',
}
Detected preset 'default' as the best matching preset for your configuration.
Visit …
```
> docs: Fix yarn command

- website/docs/options/babelConfig.md
- website/docs/options/tsconfig.md
Updated a few references in the docs, `tsConfig -> tsconfig`. Support for `tsConfig` was removed in #2127
> docs: update tsconfig option docs

- website/docs/esm-support.md
- website/docs/test-helpers.md
Related to #2270 
Green CI
**N.A.**
> docs(devs-infra): improve docs for ESM support and Test helpers

- package-lock.json
- src/__serializers__/processed-source.ts
Upgrade `js-yaml` and `@types/js-yaml` to v4
Green CI
**N.A.**
> build(devs-dep): upgrade js-yaml@4

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 27.0.0-next.3

- website/docs/troubleshooting.md
- website/sidebars.js
- Reorganizing sidebar to be more structural
- Add **Troubleshooting** section
Green CI
**N.A.**
> docs(devs-infra): reorganize sidebar and add troubleshooting section

- src/config/config-set.spec.ts
- src/config/config-set.ts
Set default module `CommonJS` after resolving tsconfig
Adjusted unit test, green CI
**N.A.**
> refactor(config): set default value `CommonJS` after resolving tsconfig

- website/docs/babel7-or-ts.md
- website/docs/debugging.md
- website/docs/e2e-testing.md
- website/docs/esm-support.md
- website/docs/installation.md
- website/docs/processing.md
- website/docs/react-native.md
- website/docs/test-helpers.md
- website/sidebars.js
Add **Debugging ts-jest** section
Green CI
**N.A.**
> docs: add **Debugging ts-jest** section

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 27.0.0-next.4

- website/docs/installation.md
Closes #2306
check out the branch, `cd website && npm ci && npm run doc`, check if the link points to correct page.
**N.A.**
> docs: correct link to `options` section

- CHANGELOG.md
- package-lock.json
- package.json
- Add missing deprecations of **v26.5.0**
- Remove `@types/json5` since the latest `json5` already included typings.
Green CI
**N.A.**
> build(devs-infra): add deprecation of 26.5 and remove @types/json5

- src/config/config-set.ts
- src/types.ts
Forgot to include in #2299
Green CI
**N.A.**
> build(devs-infra): expose `TsJestAstTransformer` as public type

- website/docusaurus.config.js
@kulshekhar docs deployed but the site doesn't load correctly so `baseUrl` needs to be adjusted
> docs(devs-infra): correct baseUrl

- website/docusaurus.config.js
Correct docusaurus config to point to correct folder for editing docs.
Closes #2326 
Run `npm run doc` locally and check if Edit link leads to correct destination.
**N.A.**
> docs(devs-infra): correct edit link location

- src/types.ts
Add #2335 to release **v26.5.1**
> feat(config): support typed config options for jest config typescript

- .eslintignore
- presets/index.d.ts
- src/cli/helpers/presets.ts
- src/presets/create-jest-preset.ts
- src/types.ts
> feat(presets): add typing for `presets` entry point

- CHANGELOG.md
- website/versioned_docs/version-26.5/getting-started/options.md
- website/versioned_docs/version-26.5/getting-started/presets.md
Add changelog and documentation related to **26.5.1**
> chore(release): 26.5.1

- src/compiler/language-service.ts
- src/config/config-set.spec.ts
- src/config/config-set.ts
Revert partially #2357 
Closes #2350
Closes #2374
Green CI
**N.A.**
> fix(compiler): exclude files in `outDir` from compiler source files

- src/utils/messages.ts
Add extra information for cannot process file error message
Green CI
**N.A**
> refactor(config): improve cannot process error message

- src/utils/messages.ts
Add extra information for cannot process file error message
Green CI
**N.A**
> refactor(config): improve cannot compile error message

- CHANGELOG.md
Update `CHANGELOG` for **26.5.2**
> chore(release): 26.5.2

- src/compiler/language-service.ts
- src/utils/messages.ts
Return original file content on emit skip of `LanguageService` and show warning message instead of throwing error.
Closes #2407 
Green CI
**N.A.**
> fix(compiler): return original file content on emit skip

- package-lock.json
- package.json
Closes #2406
Closes #2411
Green CI
**N.A.**
> fix: remove `@types/jest` from direct dep

- src/utils/logger.ts
Expose root logger as public constant
Green CI
**N.A.**
> refactor(config): expose root logger constant

- CHANGELOG.md
Update `CHANGELOG` for **26.5.3**
> chore(release): 26.5.3

- package.json
See https://nodejs.org/api/packages.html#packages_package_entry_points
Green CI
**N.A.**
> build: add `exports` field to `package.json`

- README.md
- package.json
- website/docs/introduction.md
- website/versioned_docs/version-26.5/introduction.md
- Correct `ts-jest` description to clear up confusion
- Correct a small mistake in `README`
Green CI
**N.A.**
> docs(devs-infra): correct a few things in documentation

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- package-lock.json
- package.json
- src/utils/version-checkers.spec.ts
- src/utils/version-checkers.ts
Support jest **27.0.0-next.8**
Green CI
**N.A.**
> feat: support jest **27.0.0-next.8**

- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7/package-lock.json
- src/compiler/language-service.ts
Backport fix
Closes #2513
Green CI
**N.A.**
> fix(compiler): return file content on emitSkipped for non ts/tsx files

- src/compiler/language-service.ts
- src/utils/messages.ts
Improve error message for `emitSkipped` scenario, related to #2513 
Green CI
**N.A.**
> refactor(compiler): improve error message for emit skipped

- README.md
markdown extension was missing
> Fixed License link

- .eslintrc.js
- package-lock.json
- package.json
upgrade `@types/node@14` and `eslint-plugin-jest@latest`
Green CI
**N.A.**
> build(deps-dev): upgrade `@types/node` and `eslint-plugin-jest`

- website/docs/guides/using-with-monorepo.md
- website/sidebars.js
- website/versioned_docs/version-26.5/guides/using-with-monorepo.md
- website/versioned_sidebars/version-26.5-sidebars.json
Add a new section in **Guides** to instruct users how to use `ts-jest` in a monorepo structure project.
Closes #1343 
Green CI
**N.A.**
> docs(devs-infra): add doc to use with monorepo structure project

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- e2e/__tests__/__snapshots__/logger.test.ts.snap
- package-lock.json
- package.json
- src/utils/version-checkers.spec.ts
- src/utils/version-checkers.ts
Adopt jest@27.0.0-next.9
Green CI
**N.A.**
> build(devs-infra): adopt jest@27.0.0-next.9

- CHANGELOG.md
Add missing PR link as well as commit link for `CHANGELOG`
Green CI
**N.A.**
> docs(devs-infra): link commit and PR for v26.5.6 for `CHANGELOG`

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- package-lock.json
- package.json
- src/compiler/ts-compiler.ts
- src/utils/version-checkers.spec.ts
- src/utils/version-checkers.ts
Upgrade jest to **next-11** and prettier **2.3.0**
Green CI
**N.A.**
> build(devs-dep): upgrade jest deps and prettier

- package.json
Correct typo `preset` in `package.json` to `presets`.
Close #2623 
Green CI
**N.A.**
> fix: add missing export `presets`

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- e2e/__tests__/module-kinds/__snapshots__/amd.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/commonjs.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/es2015.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/esnext.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/none.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/system.test.ts.snap
- e2e/__tests__/module-kinds/__snapshots__/umd.test.ts.snap
- package-lock.json
- package.json
Upgrade Jest deps for project and e2e templates
Green CI
**N.A.**
> build: update Jest deps

- src/compiler/__snapshots__/ts-compiler.spec.ts.snap
- src/compiler/ts-compiler.spec.ts
- src/compiler/ts-compiler.ts
Close #2650 
Updated unit tests
Green CI
**N.A.**
> feat: emit ESM codes if using ESM mode with Babel

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
- package-lock.json
Upgrade Jest deps for project as well as e2e
Green CI
**N.A.**
> build(dep-devs): upgrade Jest dependencies

- src/cli/cli.spec.ts
- src/cli/config/init.ts
> feat: link jest config types on npx ts-jest:init

- website/docs/getting-started/options.md
- website/versioned_docs/version-27.0/getting-started/options.md
I found this very minor issue in your documentation on using typescript for jest config.
> docs: correct ts config example

- package.json
- src/utils/version-checkers.ts
Resolves https://github.com/kulshekhar/ts-jest/issues/2749
> Add babel-jest to peerDependencies

- website/docs/guides/react-native.md
- website/versioned_docs/version-26.5/guides/react-native.md
- website/versioned_docs/version-27.0/guides/react-native.md
Close #2666 
Green CI
**N.A.**
> docs(devs-infra): update documentation for `react-native`

- website/docs/getting-started/options.md
- website/versioned_docs/version-27.0/getting-started/options.md
Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>
This PR fixes a minor typo in `options.md` file.
No test required as it was a minor typo in string.
> docs: fix typo in options.md

- e2e/__external-repos__/custom-typings/package.json
- e2e/__external-repos__/custom-typings/yarn.lock
- e2e/__external-repos__/memory-usage/package.json
- e2e/__external-repos__/memory-usage/yarn.lock
- e2e/__external-repos__/path-mapping/package.json
- e2e/__external-repos__/path-mapping/yarn.lock
- e2e/__external-repos__/simple-project-references/package.json
- e2e/__external-repos__/simple-project-references/yarn.lock
- e2e/__external-repos__/simple/with-dependency/package.json
- e2e/__external-repos__/simple/with-dependency/yarn.lock
- e2e/__external-repos__/yarn-workspace-composite/package.json
- e2e/__external-repos__/yarn-workspace-composite/yarn.lock
- e2e/__templates__/default/package-lock.json
- e2e/__templates__/default/package.json
- e2e/__templates__/with-babel-7-string-config/package-lock.json
- e2e/__templates__/with-babel-7-string-config/package.json
- e2e/__templates__/with-babel-7/package-lock.json
- e2e/__templates__/with-babel-7/package.json
- e2e/__templates__/with-unsupported-version/package-lock.json
- e2e/__templates__/with-unsupported-version/package.json
> build(deps-dev): update e2e deps

- .github/workflows/ci.yml
- .github/workflows/doc-generator.yml
- README.md
- website/docs/contributing.md
- website/docs/getting-started/options/astTransformers.md
- website/docs/getting-started/options/diagnostics.md
- website/docs/guides/troubleshooting.md
- website/docusaurus.config.js
- website/src/pages/versions.js
- website/versioned_docs/version-26.5/contributing.md
- website/versioned_docs/version-26.5/getting-started/options/diagnostics.md
- website/versioned_docs/version-26.5/guides/troubleshooting.md
- website/versioned_docs/version-27.0/contributing.md
- website/versioned_docs/version-27.0/getting-started/options/astTransformers.md
- website/versioned_docs/version-27.0/getting-started/options/diagnostics.md
- website/versioned_docs/version-27.0/guides/troubleshooting.md
Change CI config to run on `main` branch as well as updating doc to point to `main` branch.
Green CI
**N.A.**
> build(devs-infra): change CI config and doc to point to `main` branch

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/doc-generator.yml
- .github/workflows/release-and-publish.yml
Allow dependabot to manage github-actions dependencies
> chore(ci): setup dependabot for github-actions dependencies

- .github/ISSUE_TEMPLATE/bug.yml
Bug template has debug log section which doesn’t have unique id which makes the template not working.
**N.A.**
> docs(devs-infra): correct debug log id section

- tsconfig.build.json
- tsconfig.json
Simplify tsconfig settings for root and build config
Green CI
**N.A.**
> build(devs-infra): improve tsconfig settings

- src/transformers/path-mapping.spec.ts
- src/transformers/path-mapping.ts
> refactor(transformers): use ts transform factory APIs for `path-mapping`

- src/config/__snapshots__/config-set.spec.ts.snap
- src/transformers/__snapshots__/hoist-jest.spec.ts.snap
- src/transformers/__snapshots__/path-mapping.spec.ts.snap
- src/transformers/hoist-jest.spec.ts
- src/transformers/hoist-jest.ts
- src/transformers/path-mapping.spec.ts
Use ts `printer` and `transform` to test AST transformers in unit tests will allow us to check the original source codes after modifying the AST without compiling to `js`.
Green CI
**N.A.**
> test(transformers): use ts `printer` and `transform` apis for unit tests

- src/compiler/ts-compiler.ts
- tsconfig.build.json
Also remove unnecessary eslint disable comment
Green CI
**N.A.**
> build(devs-infra): exclude `src/__helpers__` from build process

- website/docs/getting-started/paths-mapping.md
- website/package-lock.json
- website/package.json
- website/versioned_docs/version-26.5/getting-started/paths-mapping.md
- website/versioned_docs/version-27.0/getting-started/paths-mapping.md
> docs(devs-infra): update website deps

- e2e/__tests__/ast-transformers.test.ts
- e2e/ast-transformers/transformer-in-ts/package-lock.json
- e2e/ast-transformers/transformer-in-ts/package.json
- package-lock.json
- package.json
- src/config/config-set.ts
- src/types.ts
- src/utils/importer.ts
- src/utils/messages.ts
Use on-the-fly loading `esbuild` when needed so we don't have to add to `dependencies`
Related to https://github.com/kulshekhar/ts-jest/discussions/3128#discussion-3724187
Green CI
**N.A.**
> fix: make `esbuild` as optional peer dependency

- .github/workflows/ci.yml
- .github/workflows/doc-generator.yml
Use https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
Make a new push to this branch and see if running workflows are cancelled
Red one is the previous one which is cancelled by blue one.
**N.A.**
> build: cancel previous workflows when new push on the branch happens

- website/docs/guides/esm-support.md
- website/versioned_docs/version-27.0/guides/esm-support.md
- website/versioned_docs/version-27.1/guides/esm-support.md
> docs(devs-infra): update documentation for support ESM

- website/docs/debugging.md
Current debugging docs for Windows only work if the user is running cmd/Command Prompt. This adds a section for PowerShell to make it clearer/easier for PowerShell users (which I would hope is the majority of devs on Windows these days).
N/A, documentation-only change.
> Update debugging docs to add info for PowerShell on Windows

- src/compiler/ts-compiler.ts
Closes #3272 
#3272 example should pass test
**N.A.**
> fix(compiler): revert #3194

- website/docs/getting-started/paths-mapping.md
- website/docs/guides/react-native.md
- website/versioned_docs/version-26.5/getting-started/paths-mapping.md
- website/versioned_docs/version-26.5/guides/react-native.md
- website/versioned_docs/version-27.0/getting-started/paths-mapping.md
- website/versioned_docs/version-27.0/guides/react-native.md
- website/versioned_docs/version-27.1/getting-started/paths-mapping.md
- website/versioned_docs/version-27.1/guides/react-native.md
This changes the URLs so it directly navigates to the correct documentation.
- Jest `moduleNameMapper`
- Using TypeScript with React Native
> docs: update direct links 

- website/versioned_docs/version-27.1/guides/test-helpers.md
From the [docs](https://kulshekhar.github.io/ts-jest/docs/guides/test-helpers#example). I can use the following import:
```
import { mocked } from 'ts-jest';
```
Apparently it's been moved to `ts-jest/utils`
> doc: Update test-helpers

- tsconfig.spec.json
- website/package-lock.json
- website/package.json
- website/src/pages/index.tsx
- website/src/pages/versions.tsx
- website/tsconfig.json
Upgrade docusaurus deps and use TypeScript.
Green CI
**N.A.**
> docs(devs-infra): upgrade deps and use TypeScript

- src/index.ts
- src/legacy/ts-jest-transformer.ts
- src/utils/messages.ts
Addressed by some concerns in #3453
Green CI
**N.A.**
> fix: revert deprecation message for `TsJestTransformer`

- src/legacy/compiler/compiler-utils.ts
- src/legacy/compiler/ts-compiler.spec.ts
- src/legacy/compiler/ts-compiler.ts
Fixes #3482
- Check if breakpoints are hit in JetBrains IDE
- Check if VS Code doesn't print errors.
**N.A.**
> fix(compiler): bring back compiled output with inline sourcemap

- e2e/ast-transformers/hoist-jest/package.json
- src/legacy/config/config-set.ts
Load `hoist-jest` via normal import way. This provides better type check when building source.
Green CI
**N.A.**
> refactor(devs-infra): load hoist jest transformer from import

- package-lock.json
- package.json
This PR updates the version of json5 to a version not impacted by https://github.com/advisories/GHSA-xvch-5gv4-984h.
> feat: update version of json5

- e2e/ast-transformers/hoist-jest/package-lock.json
- e2e/ast-transformers/transformer-in-ts/package-lock.json
- e2e/ast-transformers/transformer-options/package-lock.json
- e2e/config-typing/package-lock.json
- e2e/custom-compiler/ttypescript/package-lock.json
- e2e/transform-js/package-lock.json
- e2e/transform-tsx/package-lock.json
- examples/js-with-babel/package-lock.json
- examples/js-with-babel/package.json
- examples/js-with-ts/package-lock.json
- examples/js-with-ts/package.json
- examples/react-app/package-lock.json
- examples/react-app/package.json
- examples/ts-only/package-lock.json
- examples/ts-only/package.json
- package-lock.json
- package.json
> test(e2e): upgrade e2e deps

- .github/workflows/ci.yml
- .github/workflows/prepare-cache.yml
- .github/workflows/test.yml
> build(devs-infra): improve caching for CI

- src/legacy/compiler/ts-compiler.ts
Fixes #3665 
No idea how to test this, but expect CI to be green
**N.A.**
> fix(legacy): add `useCaseSensitiveFileNames` wherever needed

- package.json
This PR attempts to address https://github.com/kulshekhar/ts-jest/issues/3689, where `@types/jest` is proposed to be an optional peer dependency.
I can't imagine an appropiate test plan, I'm open to suggestions
> build(deps): update @jest/types to be an optional peer dependency

- .github/workflows/release-and-publish.yml
- Switch to Node LTS
- Use `softprops/action-gh-release` action because `create-release` is unmaintained
Have to test by creating a new tag
**N.A.**
> build(devs-infra): improve release and publish workflow

- renovate.json
- Extend rules for @commitlint
- Extend rules for @babel
- Extend rules for eslint-plugin
- Add rules for @types
> build(devs-infra): update Renovate bot config

- CHANGELOG.md
- package-lock.json
- package.json
- website/docs/guides/esm-support.md
- website/versioned_docs/version-28.0/guides/esm-support.md
> chore(release): 28.0.8

- .github/workflows/test.yml
Prepare for v29
Green CI
**N.A.**
> build(devs-infra): replace node 12 with node 18 for CI

- scripts/post-build.js
> build(devs-infra): check if git command is available for postbuild

- .github/workflows/ci.yml
Adjust `needs` of `finish` step to include also `test-windows`
Green CI
**N.A.**
> build(devs-infra): finish step should run only when all tests finish

- website/docs/getting-started/options.md
- website/docs/getting-started/options/astTransformers.md
- website/docs/getting-started/options/babelConfig.md
- website/docs/getting-started/options/compiler.md
- website/docs/getting-started/options/diagnostics.md
- website/docs/getting-started/options/isolatedModules.md
- website/docs/getting-started/options/stringifyContentPathRegex.md
- website/docs/getting-started/options/tsconfig.md
- website/docs/getting-started/options/useESM.md
- website/docs/guides/esm-support.md
- website/docs/guides/react-native.md
> docs(devs-infra): update docs to reflect transformer config

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 29.0.2

- package-lock.json
- package.json
This PR is intended to fix a security vulnerability (Prototype Pollution in JSON5 via Parse Method) described in [this issue](https://github.com/kulshekhar/ts-jest/issues/3974.)
More information on it here: https://github.com/advisories/GHSA-9c47-m6qq-7p4h
> build(deps): updated json5 dependency

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 29.1.0

- examples/monorepo-app/jest-esm-isolated.config.mjs
- examples/monorepo-app/jest-esm.config.mjs
- examples/monorepo-app/jest-isolated.config.cjs
- examples/monorepo-app/jest.config.cjs
- examples/monorepo-app/package-lock.json
- examples/monorepo-app/package.json
- examples/monorepo-app/src/welcome-message.ts
- examples/monorepo-app/tests/project-1/jest-esm-isolated.config.mjs
- examples/monorepo-app/tests/project-1/jest-esm.config.mjs
- examples/monorepo-app/tests/project-1/jest-isolated.config.cjs
- examples/monorepo-app/tests/project-1/jest.config.cjs
- examples/monorepo-app/tests/project-1/tsconfig-esm.json
- examples/monorepo-app/tests/project-1/tsconfig.json
- examples/monorepo-app/tests/project-1/welcome-message.spec.ts
- examples/monorepo-app/tests/project-2/jest-esm-isolated.config.mjs
- examples/monorepo-app/tests/project-2/jest-esm.config.mjs
- examples/monorepo-app/tests/project-2/jest-isolated.config.cjs
- examples/monorepo-app/tests/project-2/jest.config.cjs
- examples/monorepo-app/tests/project-2/tsconfig-esm.json
- examples/monorepo-app/tests/project-2/tsconfig.json
- examples/monorepo-app/tests/project-2/welcome-message.spec.ts
- examples/monorepo-app/tsconfig-esm.base.json
- examples/monorepo-app/tsconfig.base.json
> test(examples): add example repo for monorepo app

- src/types.ts
> fix: use `Config.ProjectConfig`

- src/legacy/config/config-set.ts
- src/legacy/ts-jest-transformer.ts
- src/types.ts
> build: reference transform options via jest `TransformOptions` type

- package-lock.json
- package.json
Closes #4316 
Green CI
**N.A.**
> build: upgrade deps to fix lodash security issue

- .github/workflows/release-and-publish.yml
> ci: improve release pipeline

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 29.1.5

- src/legacy/config/config-set.spec.ts
- src/legacy/config/config-set.ts
> fix: don't show warning message with Node16/NodeNext

- package-lock.json
- package.json
`commitlint` v19 requires Node >=18 which doesn't satisfy Jest supported versions
Green CI
**N.A.**
> build(deps): lock `commitlint` at v18

- website/docs/getting-started/options.md
- website/docs/getting-started/options/astTransformers.md
- website/docs/getting-started/options/babelConfig.md
- website/docs/getting-started/options/compiler.md
- website/docs/getting-started/options/diagnostics.md
- website/docs/getting-started/options/isolatedModules.md
- website/docs/getting-started/options/tsconfig.md
- website/docs/getting-started/options/useESM.md
- website/docs/guides/esm-support.md
- website/versioned_docs/version-29.0/getting-started/options.md
- website/versioned_docs/version-29.0/getting-started/options/astTransformers.md
- website/versioned_docs/version-29.0/getting-started/options/babelConfig.md
- website/versioned_docs/version-29.0/getting-started/options/compiler.md
- website/versioned_docs/version-29.0/getting-started/options/diagnostics.md
- website/versioned_docs/version-29.0/getting-started/options/isolatedModules.md
- website/versioned_docs/version-29.0/getting-started/options/tsconfig.md
- website/versioned_docs/version-29.0/getting-started/options/useESM.md
- website/versioned_docs/version-29.0/guides/esm-support.md
Closes #4264
Green CI
**N.A.**
> docs: update correct explaining comment for regex

- package-lock.json
- package.json
- src/__mocks__/thing1.ts
- src/__mocks__/thing2.ts
- src/utils/backports.spec.ts
> build: replace lodash deps with native js implementation

- src/cli/config/init.ts
- src/presets/__snapshots__/create-jest-preset.spec.ts.snap
- src/presets/create-jest-preset.spec.ts
- src/presets/create-jest-preset.ts
> refactor: change preset util function names

- renovate.json
> build: enable renovate to update deps for example react app

- renovate.json
> build: update eslint and prettier config for renovate bot

- e2e/presets/__tests__/presets.spec.ts
- e2e/presets/extended-jest-config.ts
- src/__helpers__/fakers.ts
- src/cli/__snapshots__/cli.spec.ts.snap
- src/index.ts
- src/legacy/config/config-set.spec.ts
- src/legacy/index.ts
- src/legacy/ts-jest-transformer.ts
- src/presets/__snapshots__/create-jest-preset.spec.ts.snap
- src/presets/create-jest-preset.ts
- src/types.ts
> Fix a few type issues

- e2e/presets/__tests__/presets.spec.ts
- presets/index.js
- src/cli/__snapshots__/cli.spec.ts.snap
- src/cli/cli.spec.ts
- src/cli/config/migrate.ts
> feat(cli): allow migrating CJS `presets` to `transform` options

- e2e/presets/__tests__/presets.spec.ts
- presets/index.js
- src/presets/__snapshots__/create-jest-preset.spec.ts.snap
- src/presets/create-jest-preset.spec.ts
- src/presets/create-jest-preset.ts
- src/types.ts
> feat(presets): add util functions to create ESM presets

- src/legacy/compiler/__snapshots__/ts-compiler.spec.ts.snap
- src/legacy/config/config-set.spec.ts
- tsconfig.build.json
- tsconfig.json
- tsconfig.spec.json
> build: build package with `NodeNext` module

- src/presets/__snapshots__/create-jest-preset.spec.ts.snap
- src/presets/create-jest-preset.ts
> fix: set value `ts/tsx` `extensionsToTreatAsEsm` in default esm preset

- website/docs/getting-started/options.md
- website/docs/getting-started/presets.md
- website/docs/guides/esm-support.md
- website/docs/guides/react-native.md
- website/versioned_docs/version-29.2/getting-started/options.md
- website/versioned_docs/version-29.2/getting-started/presets.md
- website/versioned_docs/version-29.2/guides/esm-support.md
- website/versioned_docs/version-29.2/guides/react-native.md
> docs: use create preset utils in doc

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
> build(deps): upgrade docusaurus to 3.6.3

- .husky/commit-msg
- .husky/post-commit
- .husky/pre-commit
- .lintstagedrc
- package-lock.json
- package.json
- renovate.json
> infra: migrate some configs

- .github/actions/setup-workspace/action.yml
- .github/workflows/ci.yml
- .github/workflows/doc-generator.yml
- .github/workflows/prepare-cache.yml
- .github/workflows/test.yml
- .lintstagedrc
> build: update CI config and `lint-staged` script

- src/legacy/compiler/ts-compiler.spec.ts
- src/legacy/compiler/ts-compiler.ts
- src/transpilers/typescript/transpile-module.spec.ts
- src/transpilers/typescript/transpile-module.ts
- src/utils/messages.ts
- website/docs/getting-started/options/isolatedModules.md
- website/docs/guides/esm-support.md
- website/versioned_docs/version-29.3/getting-started/options/isolatedModules.md
- website/versioned_docs/version-29.3/guides/esm-support.md
> fix: add some fixes for `isolatedModules: true`

- website/docs/getting-started/options/astTransformers.md
- website/docs/guides/esm-support.md
- website/versioned_docs/version-29.0/getting-started/options/astTransformers.md
- website/versioned_docs/version-29.0/guides/esm-support.md
- website/versioned_docs/version-29.2/getting-started/options/astTransformers.md
- website/versioned_docs/version-29.2/guides/esm-support.md
- website/versioned_docs/version-29.3/getting-started/options/astTransformers.md
- website/versioned_docs/version-29.3/guides/esm-support.md
See commits
Closes #3886 
Closes #3206
> docs: improve docs

- src/transpilers/typescript/transpile-module.spec.ts
- website/docs/guides/hybrid-node-module.md
- website/sidebars.js
- website/versioned_docs/version-29.3/guides/hybrid-node-module.md
- website/versioned_sidebars/version-29.3-sidebars.json
Closes #4751 
Green CI
**N.A.**
> docs: add hybrid node module doc

- website/babel.config.js
- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
See more at https://docusaurus.io/blog/releases/3.6#docusaurus-faster
Green CI
**N.A.**
> docs: improve doc build

- src/__helpers__/dedent-string.ts
- src/legacy/compiler/ts-compiler.spec.ts
- src/legacy/compiler/ts-compiler.ts
- src/legacy/ts-jest-transformer.spec.ts
- src/legacy/ts-jest-transformer.ts
- src/transpilers/typescript/transpile-module.spec.ts
See commits
Closes #4637 
Green CI
**N.A.**
> fix: compilation issues

- .npmignore
- e2e/transform-tsx/tsconfig.json
- e2e/transformer-options/tsconfig.json
- e2e/tsconfig-cjs.spec.json
- e2e/tsconfig-esm.spec.json
- e2e/tsconfig-js.json
- e2e/tsconfig-tsx.json
- jest.config.ts
- renovate.json
- src/legacy/ts-jest-transformer.spec.ts
- tsconfig.base.json
- tsconfig.build.json
- tsconfig.json
> infra: upgrade some configs

- src/cli/__snapshots__/cli.spec.ts.snap
- src/cli/config/init.ts
- src/constants.ts
Fixes #4840 
Green CI
**N.A.**
> fix(cli): init config with preset creator functions

- src/cli/__snapshots__/cli.spec.ts.snap
- src/cli/config/init.ts
Fixes https://github.com/kulshekhar/ts-jest/commit/6705713351f7f03967dbfe6eea4288761cee684d#comments
Green CI
**N.A.**
> fix(cli): fix wrong path for preset creator fns

- src/types.ts
> fix: fix `TsJestTransformerOptions` type

- src/legacy/config/config-set.spec.ts
- src/legacy/config/config-set.ts
Since this flag only works with `--noEmit` or `--emitDeclarationOnly` is enabled but `ts-jest` doesn't use those options
Fixes #4855
Green CI
**N.A.**
> fix(config): disable `rewriteRelativeImportExtensions` always
